### ISSUE TITLE
Revisió del client de NOTIB

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#177]
1 - La més important i que per ara m'he té aturat d'acabar la integració és que el client no es usable sobre JBoss 7.2.
   Mirant la implementació ho vaig poder sol·lucionar de forma senzilla, atès que només són dues classes, excepcions, que
 s'importen dins NotificacioRestClient, i que realment no són necessàries. Concretament, seria llevar aquestes dues línies:
 
14: import org.jboss.mx.util.MBeanProxyCreationException;
27: import es.caib.loginModule.client.AuthenticationFailureException;
 
  I a la línia 176, llevar-les del throws.
 
  També caldria afegir un constructor buid a NotificacioRestClient. Sé que no és estrictament necessari i sembla un doi, però això permet que el client es pugui emprar com un bean dins CDI amb el JBoss 7.2.
 
  No sé quina és la situació ara respecte el manteniment de Notib. Podrieu pujar aquest canvi i fer el deploy de l'artifcat maven del client de notib?
 
2 - La classe de test del client REST no funciona.
 
  Sembla que s'han anat afegint camps que ara són obligatoris però no s'omplen al ClientBaseTest. Concretament vaig haver d'afegir el següent al generarNotificacioV2:
 
    - Afegir usuariCodi a la notificacio
    - Afegir interessatTipus al titular i destinatari
 
3 - Hi ha qualque petit error a la documentació.
     - pàgina 5-6 RespostaConsultaEstatNotificacio no té els camps que diu
     - pàgina 15 usariCodi posa que és opcional, però és obligatori, al manco per les notificacions.

**Comment by acuevas-dgtic** [comment]
Hola,
ademas de usuariCodi  y interessatTipus, hay que añadir el campo 'dir3codi' del titular si es una administración

**Comment by areus-fundaciobit** [comment]
Afegir, respecte el punt 3 de documentació, que el `serveiTipus` de `Enviament` s'especifica que és opcional, i que per defecte val `NORMAL`, però sembla que en realitat és obligatori, i dona error si no es fixa explicitament a `NORMAL` o `URGENT`
