### ISSUE TITLE
Al crear una notificació a través de l'API amb només un titular aquesta no s'envia

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/notib#178]
Hem detectat que si es crea una notificació a través de l'API amb només un titular es crea la notificació a dins NOTIB però no es registra ni s'envia. La informació de l'enviament de la notificació a la interfície web de notib apareix buida.

**Comment by acuevas-dgtic** [comment]
Hemos modificado el código de la aplicación externa ya que parece que no se estaba añadiendo correctamente la información de destinatarios. Ahora ha llegado correctamente a Notib y Notifica. Cierro la incidencia ya que parece que no era un problema de Notib
