### ISSUE TITLE
Revisar funcionament del sistema de pooling/adviser per actualitzar l'estat de les notificacions

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/notib#179]
S'hauria de revisar el funcionament correcte del sistema de pooling i d'adviser. Quan configuram el funcionament amb pooling pareix que no actualitza l'estat de la notificació i quan està configurat l'Adviser tot i que pareix que peticions de l'adviser no s'actualitza bé l'estat de la notificació.

Per fer les proves realitzam actualització manual del canvi d'estat de la notifiació.

**Comment by acuevas-dgtic** [comment]
En PRO no nos funciona el adviser para recibir las respuestas de Notifica.

**Comment by sandreu-limit** [comment]
El 15/05 s'han afegit logs per a esbrinar si les peticions arriben , o no, i en cas que aribin en quin punt dónen error.

També s'ha realitzat una modificació a l'adviser, ja que el primer que feia era obtenir la entitat definida a Notib amb el codi de l'organisme emisor (que no es troba configurada com a entitat a Notib), el que invariablement hagués produït un error.

Quedam a l'espera de la pujada a producció de la versió 1.1.2.10 per a obtenir els nous logs.

**Comment by acuevas-dgtic** [comment]
Ya hemos desplegado la versión. Parece que no funciona el adviser ya que, una vez firmada la notificación, no llega respuesta
