### ISSUE TITLE
Revisar eventos de llamada al callback cliente

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#180]
Al realizar una notificación desde el API, pasados unos minutos, aparece un error en el registro de eventos del tipo "L'event 397397 no té referència de destinatari, no es pot fer un callback a l'aplicació client."

**Comment by josepg-limit** [comment]
Hola,
Es recomana actualitzar a la darrera versió de NOTB (1.1.2.9) que inclou vàries millors respecte a aquest tema. També s'ha de revisar que el codi de l'aplicació donada d'alta en Notib coincideix amb l'usuari de l'aplicació.

![imagen](https://user-images.githubusercontent.com/17267008/80094201-23ae3800-8566-11ea-99cd-d4cadf71d675.png)

**Comment by acuevas-dgtic** [comment]
Parece que ya funciona. Cierro la issue
