### ISSUE TITLE
Error al consultar el detalle de un notificación procesada

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#181]
En Notib, al intentar consultar una notificación procesada aparece una pantalla con el siguiente error:
javax.servlet.jsp.JspTagException: No message found under code 'enviament.datat.origen.enum.dehu' for locale 'ca'.

**Comment by josepg-limit** [comment]
Hola,
aquest origen pareix que s'ha afegit a la darrera versió de Notific@ i no està dins Notib.
Els únics valors que suporta Notib actualment són:

enviament.datat.origen.enum.correos_cie=Correos (Enviament postal)
enviament.datat.origen.enum.electronico=Adreça electrònica habilitada (DEH)
enviament.datat.origen.enum.postal=Entrega postal
enviament.datat.origen.enum.carpeta=Carpeta ciutadana
enviament.datat.origen.enum.sede=Seu electrònica
enviament.datat.origen.enum.ema=ema
enviament.datat.origen.enum.funcionario_habilitado=Funcionari habilitat

**Comment by acuevas-dgtic** [comment]
Esta incidencia se debe resolver lo antes posible
