### ISSUE TITLE
Classificar procediments administratius

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#189]
En breu es definiran multitud de procediments administratius per poder fer notificacions. Per això serà important poder agrupar aquests procediments.

Els procediments s'han d'agrupar per òrgan gestor (codi DIR3) dins d'una mateixa Entitat. En concret:
- Permetre definir permisos a nivell d'òrgan gestor i de procediments.
- Afegir columna 'Òrgan gestor' després de 'Entitat' a la Gestió de procediments.
- Afegir filtre 'Òrgan gestor' a la Gestió de procediments.
- Afegir filtre 'Òrgan gestor' a la Consulta de remeses. Només han d'aparèixer els òrgans on l'usuari tingui accés almenys a un procediment o tingui accés a tot l'òrgan gestor.
- El filtre 'Procediments' a la consulta de remeses ha de dependre de l'Òrgan gestor seleccionat.

**Comment by acuevas-dgtic** [comment]
L'alta de procediments no hauria de ser manual, s'haurien de carregar des del Rolsac, que és on es gestionen de forma única.

**Comment by acuevas-dgtic** [comment]
Aquest procediments s'han d'agrupar per codi DIR3.

**Comment by acuevas-dgtic** [comment]
S'ha d'avaluar la possibilitat d'agafar els òrgans gestors directament a partir d'una integració amb dir3caib

**Comment by acuevas-dgtic** [comment]
El punt "Permetre definir permisos a nivell d'òrgan gestor i de procediments." es farà a la #190 .

**Comment by acuevas-dgtic** [comment]
Afegir filtre al desplegable de Procediments (consulta de remeses)

**Comment by sandreu-limit** [comment]
A part dels filtres demanats, per tal de poder afegir permisos a nivell d'organ gestor, s'han realitzatels següents canvis:

- s'ha afegit un llistat de organs gestors. Aquest llistat no permet afegir o eliminar organs, sino que mostra els organs gestors dels procediments existents. L'única acció possible és actualitzar el nom de l'organ, consultant-lo al Dir3.
- s'ha afegit la opció de configurar permisos sobre els organs gestors (des del llistat d'organs gestors).

Aquests permisos encara no s'utilitzen per a controlar si es poden consultar o notificar procediments administratius (aquesta tasca es realitzarà a la issue #190). També estaria bé afegir al llistat de permisos del procediments informació dels permisos a nivell d'òrgan gestor, en mode lectura, per a que des d'un únic punt es puguin veure tots els permisos sobre el procediment.
