### ISSUE TITLE
Revisar validacions a la pantalla d'usuari de Notib

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/notib#192]
Fent proves hem detectat que per exemple si poses un NIF massa llarg, no es fa cap validació i es genera un error de base de dades. Podrieu revisar els controls que es fan a aquesta pantalla.

A part, hem detectat que encara que s'hagui produït aquest error, la notificació s'ha enviat i no hauria de ser així. Això també ho podrieu revisar.

**Comment by acuevas-dgtic** [comment]
El error de base de datos es el siguiente:
`org.springframework.orm.hibernate3.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [insert into not_persona (createdBy_codi, createdDate, lastModifiedBy_codi, lastModifiedDate, cod_entitat_desti, email, notificacio_env_id, incapacitat, interessattipus, llinatge1, llinatge2, nif, nom, rao_social, telefon, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; SQL state [72000]; error code [12899]; Could not execute JDBC batch update; nested exception is org.hibernate.QueryTimeoutException: Could not execute JDBC batch update `

**Comment by sandreu-limit** [comment]
Afegides validacions de longituds i obligatorietat als camps del
formulari d'alta del formulari.

S'ha detectat que en la API també falten validacions de longitud, i de
camps del procediments necessaris en cas d'utilització de SIR.
Queda pendent revisar la obligatorietat del nif en els titular/destinataris

**Comment by acuevas-dgtic** [comment]
Hola. Esta issue está en estado "To Do" dentro del proyecto. Entiendo que estáis en ello por lo que la paso a estado "In progress". Es conveniente que llevemos un control de las tareas que se están llevando a cabo en cada momento.
