### ISSUE TITLE
Inclusió d’annexes a la notificació

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#196]
Reconfigurar la gestió de documents a notificar/comunicar en base a la definició d’un únic document de notificació (no necessàriament ENI) i d’un conjunt d’annexes opcional. Recomana enviar versió imprimible.

**Comment by josepg-limit** [comment]
El servicio web actual de Notifica no dispone de opción para añadir documentos adjuntos a la notificación.
La opción disponible sería enviar un documento zip con el documento a notificar más los adjuntos, però tendria que revisar-se a nivel legal.

La tarea queda en suspenso hasta que se tomo una decisión al respecto.

**Comment by acuevas-dgtic** [comment]
Se permitirá añadir varios documentos en una comunicación para una administración via SIR #419
