### ISSUE TITLE
Error quan la notificació té més d'un destinatari

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#199]
Desde la web, se produce un error al intentar enviar una notificación a más de un destinatario.

**Comment by sandreu-limit** [comment]
Notifica dóna error al enviar una notificació amb més d'un enviament.
S'ha enviat la incidència al CAID (Centro de Ayuda de Integradores y Desarrolladores).

**Comment by sandreu-limit** [comment]
Des de el CAID de Madrid han contestat:

>Se ha comprobado que el problema descrito se debe al uso de dos nodos "titular" en la configuración de los envíos múltiples. 
>Una notificación únicamente debe tener un titular, si desean remitir el envío a varios receptores establezcan sus datos haciendo uso de la etiqueta "destinatarios".

Entenem que aquesta resposta no respón els que se'ls va demanar (diferents enviaments amb un titular cada enviament). Per tant enviam una nova consulta, i esperam la resposta.

**Comment by josepg-limit** [comment]
Des de CAID ens han enviat un exemple de petició i pareix que el problema és quan s'envia l'element <ns2:destinatarios/> sense informar, als dos enviaments. 
S'ha fet un canvi per resoldre el problema en la versió 1.1.4.
