### ISSUE TITLE
Notib envia dos veces una misma notificación

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#200]
Notib intenta enviar varias veces la misma notificación a Notifica. Notifica devuelve un mensaje [4160] Referencia emisor duplicada para ese Organismo, ya existe un envio con identificador 63707645eba69c775228.

![imatge](https://user-images.githubusercontent.com/58417501/81667582-c0684500-9443-11ea-9540-f8e1fda35819.png)

**Comment by acuevas-dgtic** [comment]
La primera vez sí llega a Notifica.

**Comment by sandreu-limit** [comment]
El 15/05 s'han afegit logs per a esbrinar quina és la seqüència d'accions que provoca l'enviament de notificacions ja enviades.

No ha estat possible reproduir l'error en local.
Quedam a l'espera de la pujada a producció de la versió 1.1.2.10 per a obtenir els nous logs.

**Comment by acuevas-dgtic** [comment]
Es probable que este error esté relacionado con la #178 y sea realmente un problema de la aplicación externa que no enviada bien los datos. No se ha vuelto a producir. Cierro la incidencia
