### ISSUE TITLE
Error de connexió tancada

### ISSUE THREAD

**Issue by sandreu-limit** [GovernIB/notib#202]
Es produeixen errors de connexió tancada amb molta freqüència.
D'entrada semblen provocats per la recepció de peticions de l'adviser.

**Comment by sandreu-limit** [comment]
Després d'investigar els logs de l'entorn de desenvolupament sembla que aquests errors es produeixen principalment a:
- Mètodes executats en segon pla (scheduled) per a realitzar enviaments a registre i notifica, o per actualitzar l'estat
- Servei adviser

Un cop investigats els diferents mètodes s'han detectat 2 possibles problemàtiques:
- El mètode de sincronització de l'adviser no estava marcat amb l'anotació Transactional
- Cada un dels mètodes scheduled realitzava la petició per a obtenir les notificacions pendents de processar amb un mètode fora de la transacció.

No es té la seguretat que siguin aquests els problemes que provoquen els errors de connexió tancada, però és força probable que ho puguin provocar.
Per tant s'ha procedit a esmenar aquests defectes detectats, i a pujar una nova versió.

Un cop instal·lada la nova versió s'haurà de comprovar si el problema persisteix, o si ha estat resolt.

**Comment by acuevas-dgtic** [comment]
Respecto a una nueva versión, ¿te refieres a una nueva release? La última es la 1.1.2.10

**Comment by sandreu-limit** [comment]
Se trata de desplegar la versión de la rama notib-1.1. 
No se ha generado una release específica.

**Comment by acuevas-dgtic** [comment]
Ya hemos desplegado la versión. Parece que no funciona el adviser ya que, una vez firmada la notificación, no llega respuesta

**Comment by acuevas-dgtic** [comment]
No me queda claro si esta issue está finalizada
