### ISSUE TITLE
Error en formulari d'alta de notificacions

### ISSUE THREAD

**Issue by sandreu-limit** [GovernIB/notib#205]
S'ha detectat que quan es crea una nova notificació, si hi ha algun error de validació, desapareixen els tipus d'enviament.

**Comment by sandreu-limit** [comment]
També s'ha detectat que si l'aplicació està configurada per a permetre múltiples destinataris en un mateix enviament, si es produeixen dos intents d'enviament amb errors de validació, es perden els destinataris, i a partir d'aquest moment, únicament mostra errors de validació del primer destinatari.

**Comment by sandreu-limit** [comment]
Aquesta tasca està requerint més hores de feina de les esperades degut a que al revisar l'errada inical s'han detectat altres problemes de fons.
Així, ha estat necessari refer el sistema de generació de enviaments i destinataris, ja que quan es produïen errades de validació, i es retornava a la pantalla d'alta de notificacions, al afegir o treure enviaments o destinataris es podien quedar dades inconsistents.

També s'ha detectat un bug en la llibreria del select 2 que feia que es perdessin els formats dels desplegables. Ha costat trobar l'origen de l'errada, i ha estat necessari canviar la versió de la llibrerira, a la 4.0.5.

**Comment by acuevas-dgtic** [comment]
Si lo veis necesario, se puede dividir la tarea en dos y pasar una parte a la próxima versión
