### ISSUE TITLE
Afegir monitor d'integracions

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#214]
Afegir un monitor que permeti visualitzar l'estat dels enviaments amb totes les integracions relacionades amb Notib (usuaris web, aplicacions client, Notific@, registre...). Similar al monitor que hi ha a Distribució.

Columnes:
Data | Descripció | Tipus | Temps resp. | Estat | Detalls

**Comment by josepg-limit** [comment]
S'ha afegit el monitor d'integracions amb els següents apartats:

- **Usuaris**: consulta de les dades dels usuaris
- **Registre**: Creació i consulta d'assentaments registrals, i obtenció de justificant
- **Notifica**: Alta i consulta de notificacions
- **Arxiu digital**: Obtenció de documents de l'arxiu
- **Callback de client**: Alta i consulta de notificacions del client, i avís de canvi d'estat
- **Gestió documental**: Desat de documents "temporals" (document físic enviat en la notificació per enviar a Notifica, o justificant de notificació per enviar a client)
- **Unitats administratives**: Consulta de països, provincies i municipis

S'ha aprofitat el desenvolupament per a afegir també un monitor d'excepcions no controlades a l'aplicació.
