### ISSUE TITLE
Moure Configuració d'aplicacions

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#215]
La secció "Configuració-->Aplicacions" hauria d'estar dins les accions de l'entitat

**Comment by sandreu-limit** [comment]
S'ha posat la configuració de les aplicacions a nivell d'entitat.
Per a realitzar aquesta feina ha estat necessari:

- Afegir la relació entra aplicació i entitat
- Modificar els controladors, dto, commands i jsp relacionats amb aplicacions per a afegir la entitat 
- Modificar la validació de codi d'aplicació duplicat, per a comprovar-ho per entitat, i no a nivell global
- Afegida validació a la API per tal de comprovar que l'usuari d'aplicació utilitzar per a realitzar l'alta d'una notificació es trobi donat d'alta a la entitat indicada a la notificació (codi Dir3).
