### ISSUE TITLE
Errores detectados en la versión 1.1.2.11

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#220]
En las primeras pruebas de la versió 1.1.2.11 se han detectado los siguientes errors:

- Una vez firmada la notificación, la marca como procesada peor no avisa al cliente
- Notificacions amb error al darrer callback : no muestra nada, se queda colgado
- Enviaments: No está mostrando los envios desde el dia 12/05/2020 14:53:48

- El callback llega al cliente pero falla la consulta de estado.

**Comment by sandreu-limit** [comment]
Error [Enviaments: No està mostrant els enviaments des de el dia 12/05/2020 14:53:48]:

Es mostren tots els enviaments però no ordenats. S'ha modificat el llistat per a què inicialment es mostri ordenat per ordre de creació. L'últim que s'ha creat és el primer de la llista.

**Comment by sandreu-limit** [comment]
Error [El callback arriba al client però falla la consulta d'estat]:

Els identificadors de les notificacions s'envien encriptats. Això fa qua algun d'ells pugui contenir un caracter '/', el que provoca la fallada al realitzar la consulta de l'estat de la notificació.
S'ha intentat enviar fent un urlEncode de l'identificador, però spring no ho accepta, de manera que finalment s'ha optat per a modificar la url del request, de manera que sigui el controlador qui accepti qualsevol cadena que vagi darrera de '/services/notificacioV2/consultaEstatNotificacio/' o de '/services/notificacioV2/consultaEstatEnviament/'.

**Comment by sandreu-limit** [comment]
Error [Una vegada firmada la notificació, la marca como processada però no avisa al client]:

La notificacions, enviades per una aplicació, es marcaven com a processada en el moment en que rebien un estat final de notifica, i després s'enviaven al callback per a ser enviades al client.
S'ha modificat aquest comportament per a marcar-se com a processada en el moment en que es té confirmació de que el client ha rebut l'avís de que la notificació ha canviat d'estat (Quan Notib reb un OK del notificaCanvi).

**Comment by sandreu-limit** [comment]
Error [El llistat de notificacions amb error al darrer callback : no mostra res, es queda penjat]:

Aquest llistat consulta tots els events de totes els enviaments. La manera com estava desenvolupat feia que pogues tardar més de l'esperat, i finalment tenir un error de timeout. A més el mètode no es trobava dins una transacció.

S'ha fet el mètode transaccional, i s'ha optimitzat la consulta.

**Comment by acuevas-dgtic** [comment]
Cal recordar tancar les issues resoltes
