### ISSUE TITLE
Optimització sistema d'events

### ISSUE THREAD

**Issue by sandreu-limit** [GovernIB/notib#222]
S'ha detectat que la taula d'events pot creixer de forma alarmant.
Per aquest motiu s'ha de plantejar algun sistema per a limitar el nombre de registres de la taula, com per exemple eliminar els events de les notificacions finalitzades.

**Comment by acuevas-dgtic** [comment]
En les comunicacions a administracions (enviaments SIR) s'afegeixen massa registres 

![imatge](https://user-images.githubusercontent.com/58417501/109002681-cebbe080-76a6-11eb-854f-7283f26ffeaf.png)

**Comment by acuevas-dgtic** [comment]
Notib està consultat cada 10 minuts l'estat del registre pels enviaments SIR. Aquest interval hauria de ser configurable. Volem configurar-lo de moment cada mitja hora

**Comment by acuevas-dgtic** [comment]
L'esdeveniment **Notific@ callback datat** apareix sempre dues vegades en les notificacions finalitzades i notificades

![imatge](https://user-images.githubusercontent.com/58417501/111149259-f3f88c00-858c-11eb-9af0-1bc98defd58d.png)

**Comment by acuevas-dgtic** [comment]
L'esdeveniment **Notific@ callback** datat no aporta res. Es pot eliminar una vegada finalitzada la notificació

**Comment by acuevas-dgtic** [comment]
Ara apareix això. No té sentit el darrer esdeveniment

![imatge](https://user-images.githubusercontent.com/58417501/111481885-ad916180-8733-11eb-85d2-1bafbcc8be61.png)
