### ISSUE TITLE
Afegir filtres al llistat de Notificacions amb error al darrer callback 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#223]
Permetre cercar per: data, procediment, concepte, estat, usuari / aplicació client

Afegir al llistat l'usuari client i un botó per consultar la causa de l'error

**Comment by sandreu-limit** [comment]
S'ha afegit el filtre al llistat de notificacions amb error

S'han detectat problemes de rendiment en aquest llistat degut a la necessitat de consultar els events. 
Per això s'ha afegit un booleà a la notificació per tal de informar si la notificació ha generat error al enviar l'últim canvi  d'estat al client. D'aquesta manere s'evita la necessitat de consultar els events, i es resol el problema de rendiment.

**Comment by sandreu-limit** [comment]
També s'ha hagut de modificar:

script per a marcar les notificacions amb l'últim callback amb error,ja que només tenia en compte l'últim event, i no l'últim de callback.
obtenció de error de les notificacions al llistat de notificacions, que feien ús del booleà errorUltimCallback de forma errònia.
