### ISSUE TITLE
Revisar l'artifcat maven del client

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#228]
"Fer notar que tot i que la versió de Notib és la 1.1 (1.1.2.11), l'artifcat maven del client (notib-client) del qual s'ha hagut d'incloure la dependència és la 1.2"

**Comment by josepg-limit** [comment]
S'han realitzat les modificacions necessàries per tal que la versió del client es correspongui amb la versió de l'aplicació. 
Quan es crei la propera release també es pujarà una nova versió del client on s'arregla el número de versió, i es procedirà a eliminar la versió 1.2.

**Comment by sandreu-limit** [comment]
S'ha pujat la versió amb la versió 1.1.2 (corersponent a la versió 1.1.2.x de Notib).
S'ha eliminat la versió 1.2 del repositori.
