### ISSUE TITLE
Canvi de literals a l'alta de notificació

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#233]
Tipus Enviament->Tipus d'enviament
Data enviament programada ->Data d'enviament programada
Número expedient->Número d'expedient
Tipus document-> Tipus de document
Els possibles valors de "Tipus de document" són: 'Arxiu', 'CSV' i 'UUId'. Renombrar aquests valors a: 'Document adjunt', 'CSV del document', 'UUid del document a l'Arxiu'.
Tipus interessat->Tipus d'interessat
NIF/CIF/DNI ->NIF/CIF
Codi DIR3 administració  ->Codi DIR3 de l'administració 

A més cal afegir un literal que informi dels formats permesos i la mida màxima dels documents adjunts

**Comment by sandreu-limit** [comment]
Al desenvolupar aquesta tasca s'ha detectat que no es validava la mida i el format dels documents a notificar.
S'ha obert la issue #250 per tal de resoldre aquest problema.
