### ISSUE TITLE
Error en la descàrrega de la certificació de la notificació

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#234]
S'ha detectat que a l'entorn de DEV la descàrrega de la certificació de la notificació dóna un error:

```
es.caib.notib.plugin.SistemaExternException: No s'ha trobat l'arxiu (id=null)
	es.caib.notib.plugin.gesdoc.GestioDocumentalPluginFilesystem.get(GestioDocumentalPluginFilesystem.java:106)
	es.caib.notib.core.helper.PluginHelper.gestioDocumentalGet(PluginHelper.java:463)
	es.caib.notib.core.service.NotificacioServiceImpl.enviamentGetCertificacioArxiu(NotificacioServiceImpl.java:980)
```

**Comment by sandreu-limit** [comment]
S'ha comprovat que a l'entorn de l'APB aquest error no es produeix, i fent proves en local no ha estat possible reproduir l'error. 
Es procedirà a realitzar proves a l'entorn de DEV per a veure si es pot detectar el problema.

**Comment by josepg-limit** [comment]
S'ha afegit una condició per mostrar el botó de descarregar certificació només en cas d'haver un identificador de certificació (que s'hagi guardat anteriorment).

**Comment by acuevas-dgtic** [comment]
Aquesta certificació és necessària per l'usuari. S'ha de revisar i solucionar l'error. Que no mostri el botó de la certificació no soluciona el problema

**Comment by sandreu-limit** [comment]
S'ha trobat un error als logs que ArrayOutOfBoudsException sense especificar més informació.

S'ha investigat aquest error i sembla que la llibreria utilitzada per a convertir el document rebut a l'adviser de Base64 a byte[], podria generar l'error, i fer que no es desi la certificació.
S'ha substituït la llibreria per la de Apache (org.apache.commons.codec.binary.Base64).

Queda fer les proves a l'entorn configurat amb adviser per assegurar que l'error s'hagi resolt.
