### ISSUE TITLE
Revisar el format de la data al camp Estat de la Consulta de remeses 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#237]
A la consulta de remeses, el format de la data de una notificació processada (camp Estat) no és correcte. El format correcte es dd/mm/yyyy Actualment apareix mm/dd/yyyy

**Comment by sandreu-limit** [comment]
Modificat el mètode utilitzat per donar format a la data, afegint també zeros a l'esquerra del dia i mes
