### ISSUE TITLE
Mostar detall de l'error a l'apartat Notificacions amb error al darrer callback 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#240]
A l'apartat "Notificacions amb error al darrer callback" , afegir una acció de detall per veure els detalls de l'error

**Comment by sandreu-limit** [comment]
S'ha afegit un botó de detalls que mostra en una finestra modal la data,  el tipus i la descripció de l'error, juntament amb el missatge de l'error.
