### ISSUE TITLE
No apareixen els procediments disponibles per crear notificació

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#249]
A l'hora de crear una nova notificació, només apareix un dels procediments. A més, a aquest procediment l'usuari no té accés.

![imatge](https://user-images.githubusercontent.com/58417501/85695506-61e7e500-b6d8-11ea-9a28-5b4f2a33f70d.png)

![imatge](https://user-images.githubusercontent.com/58417501/85694759-b76fc200-b6d7-11ea-9c51-f909d6558a54.png)

**Comment by sandreu-limit** [comment]
El problema ha estat més profund del que semblava, afectant a:

- Obtenció de procediments disponibles per notificar
- Consulta de notificacions
- Consulta d'enviaments

S'han hagut de refer tots els mètodes utilitzats per a obtenir els procediments disponibles per a usuari, entitat i grups, i les consultes de notificacions i enviaments.
