### ISSUE TITLE
Validar el format i mida dels documents a notificar

### ISSUE THREAD

**Issue by sandreu-limit** [GovernIB/notib#250]
Validar el format i mida dels documents a notificar.

Els formats admesos són: PDF i ZIP
La mida màxima admesa a Notifica (utilitzant el servei web amb base64) és d'un 11Mb. S'ha de consultar la mida màxima admesa pel registre per tal de agafar la mida mínima admesa.

**Comment by josepg-limit** [comment]
S'ha modificat l'aplicació per validar el format i la longitud del document.
S'ha configurat una longitud per defecte de 10MB (10635049 bytes). Aquest valor es pot canviar amb la propietat **es.caib.notib.notificacio.document.size**.
