### ISSUE TITLE
Error de format al camp descripció

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#251]
He hecho una prueba poniendo en el concepto los caracteres propios de la lengua catalana y me ha dado error.  He puesto un acento abierto   à    y la   ç    y      Ç Ha dado error, adjunto pantallazo

![imatge](https://user-images.githubusercontent.com/58417501/85850405-08051f00-b7ad-11ea-87cf-ecd27dc01297.png)

**Comment by josepg-limit** [comment]
L'error era el salt de línia al camp descripció. S'ha millorat aquesta validació per mostrar els caràcters que no són vàlids del camp concepte i descripció.

**Comment by acuevas-dgtic** [comment]
Hola, hemos realizado una prueba enviando un punt volat (·) en el texto del contenido sin saltos de línea y ha fallado. Por lo tanto, no creo que sea solo el tema del salto de línea.

![imatge](https://user-images.githubusercontent.com/58417501/85996283-db4b4480-ba04-11ea-9386-005704d75523.png)

**Comment by sandreu-limit** [comment]
En el camp de concepte i descripció no es permeten tots els caràcters. Aquesta és una limitació que ve imposada per Notifica:

![image](https://user-images.githubusercontent.com/17267037/86103443-101ad280-babd-11ea-91a9-2aa1db0a61fa.png)

Així, desgraciadament, el punt volat no és un caràcter acceptat.
