### ISSUE TITLE
Error d'enviament a persona jurídica

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#253]
Hem realitzat una prova de notificació a persona jurídica i ens ha donat l'error: "Raó social(interesado.razonSocial): El camp és obligatori". Aquest camp ha estat informat al procés d'alta, encara que als detalls de l'enviament no apareix aquest. Si apareix al desplegable dels enviaments de la notificació.

**Comment by josepg-limit** [comment]
Després de revisar el problema, s'ha detectat que a l'hora de fer un assentament registral a una persona jurídica s'estava agafant el nom de la persona en lloc de la raó social.
S'ha realitzat el canvi pertinent per informar la raó social en cas de ser una persona jurídica.
