### ISSUE TITLE
Ajax error en Consulta d'enviaments

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#255]
Amb rol administrador d'entitat, a vegades si tens prèviament una sessió oberta surt l'error: "DataTables warning: table id=enviament - Ajax error. For more information about this error, please see http://datatables.net/tn/7" dins la secció 'Consulta d'enviaments'. Aquest error no apareix si obris una finestra nova d'incògnit al navegador.

![imatge](https://user-images.githubusercontent.com/58417501/85981184-0cffe380-b9e4-11ea-890f-0230d0680b57.png)

![imatge](https://user-images.githubusercontent.com/58417501/85981216-1be69600-b9e4-11ea-86e7-86e9d75a26be.png)

**Comment by sandreu-limit** [comment]
S'ha investigat l'error i s'ha descobert el següent:

La versió de datatables utilitzada desa la informació de cada taula a una cookie del navegador.
Quan la suma de les cookies sobrepassa els 4Kb, les peticions ajax del datatable dónen l'error 

![image](https://user-images.githubusercontent.com/17267037/86111873-90463580-bac7-11ea-8fbb-fe52249ead92.png)

Aquest és un problema reconegut de la llibreria.
S'hauria d'investigar si aquest problema està resolt en la versió 1.10+

**Comment by sandreu-limit** [comment]
Les versions 1.10+ utilitzen el localStorage enlloc de les cookies.
Aquest canvi fa que ja no hi hagi problemes per la mida de les cookies.

Això  vol dir que per arreglar el problema de errors ajax en peticions de datatable seria necessari canviar la versió de la llibreria.
Aquesta seria una tasca de prou entitat com per a necessitar un anàlisi propi.

**Comment by sandreu-limit** [comment]
Es tanca aquesta incidència al haver detectat el problema, i creada la nova tasca #264 Actualitzar llibreria de datatables a versió 1.10+ que resoldrà el problema.
