### ISSUE TITLE
Capturar Llibre del registre pel codi dir3

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#260]
El camp "Llibre" a les dades de registre s'ha de capturar de RegWeb segons el codi dir3 de l'òrgan gestor. Revisar també si es pot capturar l'oficina de registre (serà l'oficina virtual casi sempre)

**Comment by josepg-limit** [comment]
Al capturar aquestes dades del regweb, el procés donava error de rollback per timeout de transacció. S'ha modificat per tal que la transacció es faci de forma individual procediment a procediment en lloc de transaccionalitat de tot el procés.

**Comment by acuevas-dgtic** [comment]
El camp llibre està buit a tots els procediments, inclòs al que ja teníem definits!!

**Comment by acuevas-dgtic** [comment]
Realment aquest camp de llibre i el d'oficina han d'estar configurats a l'òrgan gestor i no al procediment

**Comment by acuevas-dgtic** [comment]
No se muestra el libro en los datos del órgano. Hay que añadir una columan para el libro en el listado de órganos gestores
