### ISSUE TITLE
Afegir un sistema d'avisos generals

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#286]
Afegir un sistema d'avisos similar al de Distribució per poder mostrar als usuaris missatges amb diferents nivell d'avís (informació alerta, error)

**Comment by jvazquez-dgtic** [comment]
Buenos dias,
desde el perfil de usuario se puede acceder a la pantalla de gestion de los avisos (https://dev.caib.es/notib/avis), no deberia tener acceso a esta pantalla.

**Comment by acuevas-dgtic** [comment]
Revisar el ancho de las columnas. 

![imatge](https://user-images.githubusercontent.com/58417501/124117850-e5b57980-da70-11eb-8d7f-fe0690d10442.png)

**Comment by acuevas-dgtic** [comment]
El ancho sigue igual y se puede acceder a https://dev.caib.es/notib/avis como usuario
