### ISSUE TITLE
Generar un justificant d'enviament

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#295]
S'ha sol·licitat poder disposar d'un justificant d'enviament en NOTIB. Semblant al de Notific@.
Caldrà definir el format d'aquest justificant quan ens posem amb el desenvolupament. Volem que surti el codi que genera Notific@ per aquest enviament i el número de registre de sortida. Entre altres dades.

**Comment by acuevas-dgtic** [comment]
- [ ] El justificant s'ha de poder descarregar també dins dels detalls de la notificació.
- [ ] El justificant ha d'aparèixer el logo de Notib.
- [ ] El justificant ha d'aparèixer en català o castellà segons la interfície d'idioma de l'usuari.
- [ ] En el justificant ha d'aparèixer el codi i nom de l'òrgan emissor.
- [ ] En el justificant ha d'aparèixer el codi SIA i nom del procediment.
- [ ] La propietat codi de la capçalera no té sentit si surt el codi i nom de l'òrgan emissor
- [ ] El nom de les propietats nif i email no pareix correcte. No ha d'aparèixer direccio
				es.caib.notib.justificant.capsalera.direccio.nif=
				es.caib.notib.justificant.capsalera.direccio.codi=
				es.caib.notib.justificant.capsalera.direccio.email=
- [ ] Si és un justificant d'enviament no té sentit el camp Estado. 
- [ ] Si és un justificant d'enviament ha d'aparèixer la data d'enviament, no la de canvi d'estat.

**Comment by acuevas-dgtic** [comment]
El document hauria d'estar signat i descarregar-se en versió imprimible

**Comment by josepg-limit** [comment]
Respecte al darrer punt, la data actual que apareix al justificant és la data d'enviament. S'ha de tornar a fer una prova generant un justificant d'un enviament nou.

**Comment by josepg-limit** [comment]
Al final s'ha detectat el problema i s'ha resolt creant un nou camp per guardar la data d'enviament. La data d'enviament que havia anteriorment no era correcte.

**Comment by acuevas-dgtic** [comment]
- [ ] Eliminar-lo del botó accions del llistat de remeses (s'afegiran tots els document més endavant en la issue #434). De moment que surti només en els detalls.
- [ ] Renombrar el botó  de descàrrega de justificant d'enviament pel nom "Justificant d'enviament"
- [ ] Renombrar el botó  de descàrrega del document pel nom "Document enviat"
- [ ] Renombrar el botó  de descàrrega de justificant de reigstre pel nom "Justificant de registre"
- [ ] Renombrar el botó  de descàrrega de certificació pel nom "Certificació"

**Comment by acuevas-dgtic** [comment]
Si no pones ningun valor, aparence el logo de Notib en el pie del PDF. Este logo no se ve bien

![imatge](https://user-images.githubusercontent.com/58417501/102348706-8c896b00-3fa2-11eb-97d8-bf862ab8e424.png)

**Comment by acuevas-dgtic** [comment]
Si descargas varios justificantes de envio aparece un error

![imatge](https://user-images.githubusercontent.com/58417501/102349046-028dd200-3fa3-11eb-92f8-6f88087f41c5.png)

**Comment by acuevas-dgtic** [comment]
- [ ] Moure cap a la dreta el botó de Justificant d'enviament per que quedi igual que els altres
- [ ] Eliminar l'etiqueta "Justificant Notib"
