### ISSUE TITLE
Definir oficina virutal a nivell d'entitat

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#297]
Afegir un camp a la configuració de l'entitat per indicar el nom de l'oficina virtual.

**Comment by acuevas-dgtic** [comment]
El camp hauria de contenir el codi i nom de l'oficina similar al camp que apareix als procediments. A més, aquest camp apareix en blanc a tots els procediments encara que el configuris a nivell d'entitat

![imatge](https://user-images.githubusercontent.com/58417501/92108527-d54c5800-ede7-11ea-851f-7141bbf73e23.png)

**Comment by acuevas-dgtic** [comment]
No deja escribir en el desplegable de oficina para filtrar
