### ISSUE TITLE
La URL que apunta al detall de la notificació del mail d'avís d'una notificació no es forma bé

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/notib#298]
La URL que apunta al detall de la notificació del mail d'avís d'una notificació no es forma bé, si fas clic a la url apareix:

http://null/notificacio/552138

Ho podeu revisar?

**Comment by josepg-limit** [comment]
Per a que es formi la url de forma correcta és necessari tenir definida la propietat:
```
es.caib.notib.app.base.url
```
El valor dependrà de la instal·lació. 
Així a PRE seria:
```
es.caib.notib.app.base.url=https://proves.caib.es/notib
```
