### ISSUE TITLE
Pagadors postals i pagadors CIE relacionats amb l'òrgan gestor

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#310]
Actualment els pagadors postals i els pagadors CIE es relacionen amb el procediment.
S'ha de canviar, de manera que els pagadors postals i cie estiguin associats amb un òrgan gestor. El procediment està associat a l'òrgan gestor, per tant es pot obtenir el pagador a partir de l'òrgan del procediment.

**Comment by acuevas-dgtic** [comment]
També s'ha d'eliminar del llistat de procediments

**Comment by acuevas-dgtic** [comment]
S'ha replantejat en la #549
