### ISSUE TITLE
Modificar el format de la versió en el peu de pàgina

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#311]
Modificar el peu de pàgina per a que les vesrions es vegis de forma similar a la resta d'aplicacions del lot2:
Mostrar el número de versió i tot seguit entre parèntesi la data de compilació de la versió. Aquesta data no serà visible a no ser que es seleccioni el text.
Ex.
Sense seleccionar el text:
![imatge](https://user-images.githubusercontent.com/17267008/92099586-fc505d00-edda-11ea-8aff-e288dcd84640.png)

Amb el text seleccionat:
![imatge](https://user-images.githubusercontent.com/17267008/92099673-14c07780-eddb-11ea-9496-2cb7ef0448c3.png)

**Comment by acuevas-dgtic** [comment]
El formato NOTIB v1.1.4_pre1 ffb9ce2a84c232347041d81967328da6bd1b7202, ffb9ce2a84c232347041d81967328da6bd1b7202, 2020-09-14T05:39:50Z no es correcto. Tendria que ser NOTIB v1.1.4 (2020.09.11 15:00h9 con la fecha de la release. Similar a como funciona DISTRIBUCIÓ
