### ISSUE TITLE
Afegir les conselleries als òrgans gestors

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#331]
Actualment només apareixen els òrgans gestors de tipus Direcció General o Secretaria General. Han d'apareixer també les conselleries.

**Comment by josepg-limit** [comment]
Se ha añadido la propiedad 
`es.caib.notib.plugin.unitats.dir3.protocol`
para poder indicar si consultar los órganos utilizando el protocolo REST o SOAP.
Los posibles valores son "SOAP" i "REST". Si no se informa la propiedad, por defecto utiliza el protocolo REST.
