### ISSUE TITLE
Poder eliminar notificacions incorrectes

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#345]
De vegades es queden notficcaciones amb errors que no es poden corregir i volen poder eliminar-les.
Potser si al modificar-les és suficient (#346), l'opció d'eliminar no té sentit.

**Comment by acuevas-dgtic** [comment]
No s'ha de poder eliminar notificacions ja enviades. Només notificacions que hagin donat error de registre o de comunicació amb notifica però no si estan en estat enviades o finalitzades.

![imatge](https://user-images.githubusercontent.com/58417501/102345969-7679ab80-3f9e-11eb-8106-9d7e4ae35ce0.png)

**Comment by acuevas-dgtic** [comment]
Tampoc s'han de poder editar una vegada enviades

**Comment by acuevas-dgtic** [comment]
L'administrador també ha de poder editar o eliminar notificacions o comunicacions no enviades

**Comment by acuevas-dgtic** [comment]
Ara surt l'opció pels administradors d'entitat però no als administradors d'òrgan
