### ISSUE TITLE
Revisar data de caducitat

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#347]
La data de caducitat no s'està calculant correctament. Al procediment tenim configurat 10 dies però en surten 12

![imatge](https://user-images.githubusercontent.com/58417501/96115389-253e3480-0ee7-11eb-82c4-2c7742d5848d.png)
![imatge](https://user-images.githubusercontent.com/58417501/96115493-53237900-0ee7-11eb-933a-64a0e89ed53b.png)

**Comment by josepg-limit** [comment]
Els dies que s'estan sumant són dies feiners.

**Comment by acuevas-dgtic** [comment]
La fecha de caducidad está configurada en 10 días y yo sólo cuento 9 hábiles. Además, según el art 30.3 el plazo debe contarse a partir del día siguiente a la notificación. Por lo tanto, la fecha de caducidad debería ser el 29 en el ejemplo

**Comment by acuevas-dgtic** [comment]
Hola. acabo de confirmar que son dias naturales y no hábiles. Disculpad la confusión

"Art 43.2 Cuando la notificación por medios electrónicos sea de carácter obligatorio, o haya sido expresamente elegida por el interesado, se entenderá rechazada cuando hayan transcurrido diez días naturales desde la puesta a disposición de la notificación sin que se acceda a su contenido" .

**Comment by acuevas-dgtic** [comment]
Hay que contar 10 dias naturales desde la notificación. En el ejemplo deberia ser entonces el dia 24

**Comment by acuevas-dgtic** [comment]
Perdon dia 25
