### ISSUE TITLE
Desapareix el registre d'actualització manual de procediments

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#358]
Una vegada finalitzat el procés manual d'actualització de procediments desapareix el registre d'accions

**Comment by josepg-limit** [comment]
Es va solucionar en una altre issue de la versió 1.1.8

**Comment by acuevas-dgtic** [comment]
No se solucionó. Sigue desapareciendo

![imatge](https://user-images.githubusercontent.com/58417501/108209703-e3d6c380-712a-11eb-818b-f92ffe842c6e.png)
