### ISSUE TITLE
Error camp descripció del formulari d'alta

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#372]
Pareix que hi ha un problema amb certs caràcters dins del camp descripció. L'usuari ha introduït per exemple el següent text i li dóna un error no controlat:

`Tramesa de la resolució del director general de Consum i finalització del procediment / Remisión de la resolución del director general de Consumo y finalización del procedimiento`

`org.springframework.orm.hibernate3.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [insert into not_notificacio (createdBy_codi, createdDate, lastModifiedBy_codi, lastModifiedDate, caducitat, com_tipus, concepte, descripcio, document_id, emisor_dir3codi, entitat_id, env_data_prog, env_tipus, callback_error, estat, estat_date, grup_codi, motiu, not_env_data, not_env_intent, not_error_event_id, not_error_tipus, registre_num_expedient, organ_gestor, pagador_cie_id, pagador_postal_id, procediment_id, proc_codi_notib, registre_data, registre_env_intent, registre_numero, registre_numero_formatat, retard_postal, tipus_usuari, usuari_codi, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; SQL state [72000]; error code [12899]; Could not execute JDBC batch update; nested exception is org.hibernate.QueryTimeoutException: Could not execute JDBC batch update `

![imatge](https://user-images.githubusercontent.com/58417501/97411785-04bba480-1901-11eb-957a-65f387f074f2.png)

**Comment by acuevas-dgtic** [comment]
También me da este error, que es el apóstrofe de contracción en catalán, que el NOTIB me dice que no lo acepta.

**Comment by acuevas-dgtic** [comment]
Ya no se produce el error no controlado pero no valida el siguiente texto:
`Trasllat d'al·legacions de l'empresa i comunicació d'empresa adherida a l'arbitratge de transports / Traslado alegaciones de empresa y comunicación de adhesión de empresa  a arbitraje de transportes`

**Comment by josepg-limit** [comment]
S'han realitzat vàries proves amb el text 
`"Trasllat d'al·legacions de l'empresa i comunicació d'empresa adherida a l'arbitratge de transports / Traslado alegaciones de empresa y comunicación de adhesión de empresa a arbitraje de transportes"`
a l'entorn de desenvolupament, sense error.

![image](https://user-images.githubusercontent.com/17267008/98539812-39c6e000-228d-11eb-9e0d-1d2d793e7df6.png)

S'hauria de comprovar que no s'hagi introduït algun altre caràcter no vàlid.
Els caràcters admesos són els següents:
`" aàáäbcçdeèéëfghiìíïjklmnñoòóöpqrstuùúüvwxyzAÀÁÄBCÇDEÈÉËFGHIÌÍÏJKLMNÑOÒÓÖPQRSTUÙÚÜVWXYZ0123456789-_'\"/:().,¿?!¡;·"`
