### ISSUE TITLE
Afegir reintents a la generació del justificant de registre

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#374]
Si l'arxiu falla en un moment concret i no es pot generar el justificant de registre no hi ha manera de tornar-lo a generar. S'hauria d'afegir un sistema de cues de generació de justificants de registre en aquests casos i una opció per generar-lo manualment.

**Comment by josepg-limit** [comment]
Per descarregar el justificant es fa una consulta directe al Registre cridant el mètode **obtenerJustificante**, aquesta consulta es fa cada vegada que es vol descarregar el justificant. Segons la documentació de Registre el mètode obtenerJustificante genera el justificant si no s'ha generat prèviament al procés de creació.
![imagen](https://user-images.githubusercontent.com/17267008/99670445-d6009c00-2a70-11eb-9ac9-f5302fc9f76d.png)

Simplement s'ha afegit un missatge d'error en cas de no trobar el justificant.

**Comment by acuevas-dgtic** [comment]
Pareix que aquest mètode no genera el justificant. Existeix altre mètode?

**Comment by josepg-limit** [comment]
Segons la documentació del Registre no hi ha cap altre mètode.
Si el registre no retorna justificant s'haurien de demanar logs de registre.

No sabem si s'està desenvolupant una API REST.

**Comment by acuevas-dgtic** [comment]
Haré la consulta
