### ISSUE TITLE
Afegir  òrgan superior a la gestió d'òrgans

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#390]
- [x] Permetre cercar òrgans pel seu òrgan superior
- [x] Afegir columna al llistat de resultats amb l'òrgan superior
- [x] Controlar l'accés dels administradors d'òrgan per que només gestionin els òrgans als que tinguin accés

**Comment by acuevas-dgtic** [comment]
Falta afegir el cercador d'òrgan pare en la vista en arbre

**Comment by jvazquez-dgtic** [comment]
auto-expandir l'arbre perquè sigui visible fins l'òrgan que estem cercant

**Comment by acuevas-dgtic** [comment]
Sigue sin aparecer el campo "padre" en la vista árbol. Además, aparece desplegado cuando debería estar sin desplegar y desplegarse cuando se realiza una búsqueda

**Comment by acuevas-dgtic** [comment]
- [ ] Vista arbre: Modificar literal "Selecciona un òrgan per.." per "Òrgan superior".
- [ ] Vista arbre: Pujar el desplegable una línia i baixar els botons de netejar i filtrar.
- [ ] Vista taula: La columna Codi pare surt en blanc.
- [ ] Vista taula: Falta afegir el nom de l'òrgan pare.
- [ ] Vista taula: es pot eliminar la columna Oficina entitat.
- [ ] Vista taula: Moure les opcions "Procediments" i "Serveis" després de l'opció "Actualitzar òrgan" i abans d'Esborrar

**Comment by acuevas-dgtic** [comment]
El filtre Codi pare hauria de ser un desplegable amb el codi i nom de l'òrgan. Ha d eposar òrgan superior

**Comment by acuevas-dgtic** [comment]
Aixó en la vista taula
