### ISSUE TITLE
Problemes amb la paginació del òrgans i els procediments

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/notib#395]
Després de filtrar un llistat i que surtin vàries pàgines i editar un dels elements (de permisos o modificar), i després pitjar el boto de tornar, s'en va a la primera pàgina un altre vegada, això fa que si tens que editar molts d'elements de la mateixa pàgina tenguis que tornar a la pàgina en la que estaves.

En el cas dels procediments tampoc s'enrecorda dels parametres del llistat (v procediments comuns queda desmarcat) tot i que el filtrat el segueix fent bé

**Comment by acuevas-dgtic** [comment]
Tampoc recorda el número de registres a mostrar per pàgina

**Comment by acuevas-dgtic** [comment]
He editat un procediment i no ha recordat la pàgina
