### ISSUE TITLE
Problemes d'accés per rol com a adminsitardor d'òrgan

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#409]
Hem detectat casos d'usuaris que no poden accedir com a administradors d'òrgan encara que tinguin assignat el rol corresponent. Si donam permís directe per usuari sí poden accedir, però per rol no. Hem comprovat vàries vegades que l'usuari tengui el rol assignat, hem buidat cachés, i ha tornat a accedir-hi des d'altre navegador i finestra d'incògnit.

**Comment by acuevas-dgtic** [comment]
El problema ha sorgit en varis administradors de tota la conselleria

**Comment by acuevas-dgtic** [comment]
Pareix que es produeix si l'òrgan té òrgans dependents

**Comment by josepg-limit** [comment]
No s'ha pogut reproduïr l'error.

Tasques realitzades:
- Borrar la caché de rols d'usuaris al assignar un permís a òrgan
- Afegir traces per a visualitzar permisos (per generar traces cal afegir la propietat: es.caib.notib.permisos.organ.logs=true)
