### ISSUE TITLE
No es pot marcar com a processat

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#413]
Si l'usuari vol marcar com a processat una remesa, li permet escriure el motiu però després el botó "Marcar" no fa res.

![imatge](https://user-images.githubusercontent.com/58417501/99960638-5be05800-2d8d-11eb-89b2-ad371a572141.png)

**Comment by josepg-limit** [comment]
No s'ha pogut reproduïr el problema.
S'han realitzat les modificacions oportunes per que si hi ha un error, enlloc de tornar-se a mostrar la modal de marcar com a processat, sense informar de cap problema, es mostri un error a l'usuari, i als logs.
D'aquesta manera si torna a passar, podrem consultar els logs per a detectar el problema real.
