### ISSUE TITLE
Canvis a les dades de l’assentament registral

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#415]
Durant l'assentament registral hi ha una sèrie de camps que s’han d’informar correctament.

Classe «AsientoRegistral»
    • Atribut «**tipoTransporte**» no s’ha d’informar. És un camp per assentaments físics. Al ser optatiu, no haurà problema de deixar-lo buit.
    • Atribut «**aplicacionTelematica**» ha de contenir el nom de l’aplicació client i la seva versió. EX: «NOTIB v.1.0»
    • Atribut «**resumen**». L’extracte de l’assentament registral ha d’informar de quina operació s’ha realitzat. Ha de distingir si l’assentament correspon a una notificació o una comunicació. Hauria d’incloure el text del camp concepte de l’enviament de NOTIB.
      Per exemple:
        ◦ «Comunicacio - ‘Petició informe impacte de l’expedient 3939/20’»
        ◦ «Notificació - ‘Proposta resolució sanció EXP ATM 525/20’»
    • Atribut «**idioma**». L’ha de seleccionar l’usuari:
        ◦ 1: Català
        ◦ 2: Castellà

**Comment by acuevas-dgtic** [comment]
El camp idioma hauria d'estar seleccionat per defecte segons l'idioma de la interfície de l'usuari.

**Comment by acuevas-dgtic** [comment]
Me informan que el campo aplicacionTelematica sigue sin actualizarse
• Atribut «aplicacionTelematica» ha de contenir el nom de l’aplicació client i la seva versió. EX: «NOTIB v.1.0»

**Comment by josepg-limit** [comment]
Comprobado que el envio a Registro envia el campo aplicacionTelematica informando la versión de Notib

![image](https://user-images.githubusercontent.com/17267008/109935620-11e10980-7cce-11eb-951d-68dcc4e649d9.png)
