### ISSUE TITLE
Canviar les peticions SOAP per peticions REST (API firma simple) cap a Portafib

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#429]
En descarregar el justificant d'enviament es fa una petició SOAP al següent servei: https://proves.caib.es/portafib/ws/v1/PortaFIBPassarelaDeFirmaEnServidor per signar en servidor. S'ha de canviar perquè totes les funcionalitats cridin a serveis REST i no hi hagi peticions SOAP cap a Portafib.

**Comment by acuevas-dgtic** [comment]
El justificant d'enviament no està firmat

**Comment by josepg-limit** [comment]
hem comprovat el funcionament de la firma en servidor a DEV i no funcionava degut a que faltava canviar la classe que gestiona la firma, indicant la FirmaSimpleServidorPluginPortafib.


![Selecció_055](https://user-images.githubusercontent.com/17267008/144575663-24b475e1-dea9-4907-b799-92729767e7e9.png)

Un cop canviada aquesta propietat el justificant s'ha generat amb firma.

![Selecció_056](https://user-images.githubusercontent.com/17267008/144575710-aeb52930-dac8-4302-8fc4-1a70a9d5f4ce.png)

![Selecció_057](https://user-images.githubusercontent.com/17267008/144575727-947189b6-4b12-4630-8bb6-011506bcbc02.png)
