### ISSUE TITLE
No funcionen les metriques

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#430]
No apareix res a la pàgina

![imatge](https://user-images.githubusercontent.com/58417501/101892598-e1dd0b00-3ba3-11eb-9cfc-ceb57dc0f1c2.png)

**Comment by josepg-limit** [comment]
Comprobar si después de consultar las métricas en una ventana de incógnito, siguen funcionando en la sessión que ya se tenia abierta

**Comment by acuevas-dgtic** [comment]
Sigue igual. Si abro una ventana nueva de incógnito sí se visualizan
