### ISSUE TITLE
El nom del fitxer dins carpeta no coincideix amb el nom del fitxer dins notib

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#431]
Comprovar que el nom del document que s'envia a Notifica és el nom del fitxer i no el concepte segon es mostra en la següent captura

![imatge](https://user-images.githubusercontent.com/58417501/101896386-38991380-3ba9-11eb-9483-1a91dcc7a2e3.png)
![imatge](https://user-images.githubusercontent.com/58417501/101896340-25864380-3ba9-11eb-937e-910f2563abe4.png)

**Comment by josepg-limit** [comment]
Consultando la API de AltaRemesaEnvios de notifica, se ha comprobado que el servicio no ofrece ningún campo para informar el nombre del documento.
La API define un objeto Documento con los siguientes campos:
 - **contenido**: contenido en base 64 del documento
 - **hash**: hash del documento previamente codificado en base64
 - **enlaceDocumento**: url donde se encuentra el documento del envío
 - **metadatos**: metadatos extra del propio documento en formato XML. Concretamente los metadatos aceptados són:
     - retardo
     - caducidad
     - plazo
     - postalExterno
     - metadatos públicos (no disponible en carpeta ciudadana)
 - **opcionesDocumento**: Opciones que tiene el documento. Concretamente:
     - normalizado
     - generar CSV

En ninguno de los anteriores campos se puede especificar el nombre del documento. Por lo tanto, actualmente no es possible hacer que en la carpeta ciudadana se muestre el nombre del documento.
