### ISSUE TITLE
reintentar notificacions pendents (accions massives)

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/notib#437]
reintentar notificacions pendents (accions massives): Error AJAX: [500] Error Interno del Servidor

**Comment by acuevas-dgtic** [comment]
L'error es produeix en l'acció "Reintentar notificacions pendents"

![imatge](https://user-images.githubusercontent.com/58417501/102990791-48551800-4518-11eb-997a-13f33b56ec67.png)

**Comment by josepg-limit** [comment]
No es controlava quan alguna notificació donava error en el reintent, provocant un error AJAX 500.

S'ha modificat el funcionament per a que en el cas que alguna notificació dóni error, continüi amb la resta de notificacions, i al final mostri un missatge d'error per cada una de les notificacions que han fallat.
