### ISSUE TITLE
Afegir una cua d'enviaments per reduir el temps d'espera

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#451]
Actualment l'usuari ha d'esperar una estona molt llarga fins que l'enviament es realitza (registre+notifica). L'usuari només hauria d'esperar a que es validés el formulari i es pugés el document al servidor de Notib.

Una vegada validat el formulari, s'hauria de mostrar l'enviament com "Pendent" en la consulta de remeses i afegir-lo a una cua d'enviaments en segon pla que anés realitzant els enviaments progressivament. L'administrador d'entitat hauria de poder consultar l'estat de la cua i forçar els seleccionats per que s'enviïn immediatament.

**Comment by josepg-limit** [comment]
Al final s'ha decidit activar el mode de comunicació asíncron i visualitzar les notificacions pendents a la pantalla de remeses.

**Comment by acuevas-dgtic** [comment]
Hem activat el mètode ASINCRON i ara no s'envia ni se registra. Queda sempre en estat PENDENT. Ja han passat 5 minuts.

![imatge](https://user-images.githubusercontent.com/58417501/107353483-62998400-6acd-11eb-9b83-33ed2c8b6008.png)

**Comment by acuevas-dgtic** [comment]
Ja s'ha enviat però ha tardat 15 minuts des de la seva creació!!!

![imatge](https://user-images.githubusercontent.com/58417501/107355797-43502600-6ad0-11eb-9bce-a1e0e9494418.png)

**Comment by acuevas-dgtic** [comment]
S'ha ajustat els paràmetres període i processar.max
