### ISSUE TITLE
Falta el procediment en el formulari d'edició i problema amb el camp "Raó social" una vegada tornat a enviar

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#454]
Si s'edita una remesa pendent amb error, el procediment no apareix seleccionat en el formulari d'enviament

![imatge](https://user-images.githubusercontent.com/58417501/103861142-38633980-50bd-11eb-9cbc-ae0f13da2606.png)
![imatge](https://user-images.githubusercontent.com/58417501/103861189-4fa22700-50bd-11eb-983d-b1ff69b7c06f.png)

**Comment by acuevas-dgtic** [comment]
A més, al enviar dóna sempre l'error "[4210] Indique el nombre o razon social",e ncara que tengui un nom asignat en el formulari

**Comment by acuevas-dgtic** [comment]
Revisando el código del commit veo que se ha solucionado el tema de la razón social, pero no veo nada del procedimiento al editar

**Comment by josepg-limit** [comment]
El problema del procedimiento no lo hemos podido reproducir y al revisarlo con más detalle vimos que se solucionó en un commit anterior (https://github.com/GovernIB/notib/commit/444c0393189534d1de79203d97705503e57a0b7a).
