### ISSUE TITLE
Poder filtrar remeses de procediments comuns enviades desd'un organisme concret

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#457]
No es pot cercar les remeses d'un procediment comú enviat des d'un organisme específic donat que els procediments comuns pertanyen a l'entitat. Els administradors d'entitat i d'òrgan han de poder cercar totes les remeses enviades des d'un organisme concret. Els usuaris han de poder cercar les remeses dels procediments comuns als que tenguin accés per un òrgan concret.

**Comment by josepg-limit** [comment]
Els diferents tipus d'usuari en els filtres d'organ i procediment veuran:
- [ ] Usuaris
    - Òrgans: 
        - òrgans sobre els que disposen de permisos de consulta
        - òrgans sobre el que es disposa de permís sobre algún procediment comú
    - Procediments: procediments sobre els que l'usuari disposa de permís de consulta (inclosos comuns amb permisos en un òrgan concret) 
    - Procediments amb òrgan seleccionat: procediments de l'òrgan i procediments comuns sobre el que l'usuari disposa de permisos en l'òrgan
- [ ] Administradors d'entitat
    - Òrgans: tots els òrgans de l'entitat
    - Procediments: tots els procediments
    - Procediments amb òrgan seleccionat: procediments de l'òrgan  + procediments comuns
- [ ] Administrador d'òrgan
    - Òrgans: òrgan actual + tots els òrgans fills
    - Procediments: tots els procediments de l'òrgan actual i òrgans fills
    - Procediments amb òrgan seleccionat: procediments de l'òrgan  + procediments comuns

**Comment by acuevas-dgtic** [comment]
Estan apareixent resultats d'altres organismes  al cercar un procediment comú  enviat des d'un organisme concret

![imatge](https://user-images.githubusercontent.com/58417501/107328597-438bf980-6aaf-11eb-9cbb-93f9953a4ef6.png)
