### ISSUE TITLE
Mostrar un missatge d'error si no es possible obtenir les metadades o els documents des de CSV

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#485]
S'ha de mostrar abans d'enviar.

**Comment by josepg-limit** [comment]
S'han augmentat hores perquè s'està afegint optimització per no consultar els documents de l'arxiu més del necessari. Es guardarà informació localment.
També cal mostrar els camps de metadades en el formulari d'alta quan no es poden obtenir.
