### ISSUE TITLE
Optimització llistat de remeses i enviaments

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#492]
Per tal de millorar la resposta dels llistats de remeses i enviaments es crearan dues noves taules que tindran la informació necessària per a cada un dels llistats.

Les dades d'aquestes taules es crearan al donar d'alta una notificació, i s'actualitzaran quan hi hagi un canvi en l'estat de la notificació i/o enviaments.
En principi es planteja utilitzar AOP per a definir els punt on s'ha d'actualitzal la informació, de manera que es centralitzi el procés d'actualització de dades en un únic punt.

**Comment by acuevas-dgtic** [comment]
Al realitzar un nou enviament desapareix el camp "Emissor"

![imatge](https://user-images.githubusercontent.com/58417501/117648822-fd6a3300-b18e-11eb-9bd8-e852cd2de317.png)
![imatge](https://user-images.githubusercontent.com/58417501/117648872-11159980-b18f-11eb-8357-4b93e96ccc7c.png)

**Comment by acuevas-dgtic** [comment]
En la consulta d'enviaments sempre surt el codi d l'entitat i no de l'òrgan emissor

![imatge](https://user-images.githubusercontent.com/58417501/117651246-08729280-b192-11eb-969b-724c0d1d7b34.png)
![imatge](https://user-images.githubusercontent.com/58417501/117651337-22ac7080-b192-11eb-874e-6f6a5774b7fc.png)

**Comment by acuevas-dgtic** [comment]
Si modifiques el nom del procediment i possiblement el d'òrgan no s'actualitza el llistat de remeses

**Comment by acuevas-dgtic** [comment]
Pensándolo mejor creo que es mejor que no se actualice tal y como está ahora. Así tenemos la información real sobre el envío que se realizó
