### ISSUE TITLE
Revisar procés d'actualització d'enviaments expirats

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#493]
Cada dia tenim que executar el procés manual d'actualització de notificacions expirades. Aquest procés s'hauria d'executar automàticament

**Comment by acuevas-dgtic** [comment]
He executat el procés manual i una vegada finalitzat l'he tornat a executar i continuen havent notificacions pendents.

**Comment by acuevas-dgtic** [comment]
Tenim la versió 1.1.10 en producció però encara queden notificacions expirades sense actualitzar. Avui dilluns he tornat a executar el procés i s'han actualitzat més de 30. Aquest procés no hauria de mostrar cap notificació pendent

**Comment by josepg-limit** [comment]
Falta provar en un entorn real
