### ISSUE TITLE
Revisar missatge d'error al borrar procediment

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#494]
`Error al borrar procediment.... org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [delete from not_procediment where id=?]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update `

**Comment by josepg-limit** [comment]
Pareix que aquesta issue ja es va solucionar en alguna altre tasca. No l'hem poguda replicar
