### ISSUE TITLE
Referencia emisor duplicada para ese Organism

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#502]
Hi ha casos d'integracions via API on es duplica els enviaments a Notifica i dóna error. Això ha ocorregut executant accions massives sobre notificacions en estat "Enviant" que no s'enviaven

![imatge](https://user-images.githubusercontent.com/58417501/114034007-1628b580-987e-11eb-8950-9a70881c8f49.png)

**Comment by josepg-limit** [comment]
solucionada con la #501
