### ISSUE TITLE
No es mostren les columnes tipus d'enviament ni codi Notib enviament en la consulta d'enviaments

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#505]
![imatge](https://user-images.githubusercontent.com/58417501/114983253-ab383980-9e90-11eb-8b50-f9ec66800080.png)

![imatge](https://user-images.githubusercontent.com/58417501/114983306-c014cd00-9e90-11eb-858d-b7ac77a8fd09.png)

**Comment by josepg-limit** [comment]
El codi notib l'hem definit com la referència a notifica que només tenen els enviaments creats per API rest
