### ISSUE TITLE
Retorn a la pantalla d'enviament sense cap error

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/notib#509]
Quan se fa un nou enviament, per certs codis dir3, (comunicacio a una administració) quan tens ple el formulari d'enviament, i li dones a enviar, retorna al mateix formulari, sense cap error ni haver fer l'envio. Per exemple pasa amb els dir3 de produccio: L03070001 i L03070006

**Comment by acuevas-dgtic** [comment]
El error se está produciendo con frecuencia. Esta mañana lo he detectado en una comunicación en la que había un documento con un nombre algo largo

![imatge](https://user-images.githubusercontent.com/58417501/116964834-c1c1fb80-acac-11eb-8dca-f74c0d6f271a.png)

**Comment by acuevas-dgtic** [comment]
Los dos casos que he detectado esta mañana se producían en comunicaciones a administraciones
