### ISSUE TITLE
Canvis en el justificant d'enviament

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#522]
En el justificant d'enviament caldria afegir el camp descripció de la notificació / comunicació i una taula amb les dades dels fitxers annexos enviats (de manera similar a la que apareix en el justificant de registre)

**Comment by josepg-limit** [comment]
Es va a afegir lògica per poder obtenir el codi CSV de tots els documents que estiguin en arxiu i així poder mostrar-ho en la taula d'annexos.

**Comment by acuevas-dgtic** [comment]
- La informació dels documents ha d'apareixer al final del justificant (després dels enviaments) i sense salt de pàgina.
- Si ha ha un camp opcional no informat (per exemple Segon llinatge) no ha d'apareixer "Null"
- Una vegada generat el justificant hauria de desaparèixer la modal 

![imatge](https://user-images.githubusercontent.com/58417501/124120641-472b1780-da74-11eb-878a-439558837c43.png)

**Comment by acuevas-dgtic** [comment]
Ahora sale un error AJAX después de generar el justificante. La modal no se cierra aunque el justificante sí se genera

**Comment by acuevas-dgtic** [comment]
El texto "Aquesta notificació té els documents que es detallen a continuació..." debería estar al lado de la tabla de documentos"

**Comment by acuevas-dgtic** [comment]
Hay que hacer algunos cambios en literales:

- Si es una comunicación debería aparecer el título "JUSTIFICANT D'ENVIAMENT DE **COMUNICACIÓ** ELECTRÒNICA"
-  Si es una comunicación debería aparecer el texto "Aquesta **comunicació** té la **següent** descripció.
- Falta següent "Aquesta notificacio té la **següent** descripció.
-  Si es una comunicación debería aparecer el texto "Aquesta **comunicacio** té un total de 1 enviaments que es detallen a continuació"
- El logo de Notib debería aparecer en la cabecera después del logo del govern en lugar del pie de página.

**Comment by acuevas-dgtic** [comment]
Abaix a l'esquerre del justificant hi ha un rectangle buid
