### ISSUE TITLE
Cercador d'òrgans: columna SIR

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#535]
- [x] La columna SIR ha d'indicar si l'organisme disposa d'oficina SIR
- [x] Els organismes de la pròpia entitat no s'han de poder seleccionar
- [x] Els organismes sense oficina SIR no s'han de poder seleccionar
- [x] Afegir validacions a la API REST

**Comment by acuevas-dgtic** [comment]
Aunque ahora no aparece el botón de seleccionar cuando la oficina no es sir en una comunicación permite seleccionarla haciendo doble clicc

**Comment by acuevas-dgtic** [comment]
Solucionado
