### ISSUE TITLE
Afeir un avis d'òrgan obsolet en els desplegables i llistats

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#551]
S'hauria de mostrar un avis d'òrgan obsolet a tots el desplegables i llistats on aparegui aquest camp

![imatge](https://user-images.githubusercontent.com/58417501/121164451-e3844480-c84f-11eb-8f86-8daf59068660.png)

**Comment by acuevas-dgtic** [comment]
També s'hauria d'afegir una columna i un filtre "Vigent" en el llistat d'òrgans

**Comment by josepg-limit** [comment]
Se reabre la issue para añadir la columna y el filtre por estado "Vigent/Obsolet" en el listado de órganos. También para añadir que cuando se actualicen los órganos gestores desde dir3 mediante el botón de actualización de la interfaz web, se actualice también el estado en las tablas utilizadas para visualizar los listados de remesas y envíos.

**Comment by josepg-limit** [comment]
El desarrollo ha sido más costoso de lo esperado debido a que: se han tenido que crear scripts de BD, modificar 6 listados, 3 filtros, añadir  columna y el filtro por estado "Vigent/Obsolet" en el listado de órganos. También tener en cuenta que cuando se crean/modifican notificaciones o envíos se tiene que añadir ese nuevo estado del órgano. También añadir que cuando se actualicen los órganos gestores desde dir3 mediante el botón de actualización de la interfaz web, se actualice también el estado en las tablas utilizadas para visualizar los listados de remesas y envíos.

**Comment by acuevas-dgtic** [comment]
En la consulta de remeses apareix duplicat

![imatge](https://user-images.githubusercontent.com/58417501/124463208-d5640e00-dd92-11eb-8058-f2d500f2371e.png)
