### ISSUE TITLE
Separar tipus d’enviament a la interfície

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#553]
Hem detectat que hi ha molta confusió sobre com fer els enviaments. En lloc de fer el tipus d’enviament que toca, moltes vegades es fa servir “el primer que funcioni”, correspongui jurídicament o no (p. e. notificar en lloc de comunicar).
Proposta

Tot i que s’està fent feina en informar i sensibilitzar sobre quina comunicació pertoca a cada cas, seria desitjable disposar d’una interfície d’usuari més dirigida, que indiqui de bon començament el tipus d’enviament que es vol fer. Per exemple una cosa semblant a això:

![imatge](https://user-images.githubusercontent.com/58417501/122387134-d8779580-cf6e-11eb-90cf-d234f7af2399.png)

Quan es triï una de les opcions d’enviament, el formulari que aparegui ja hauria de mostrar el formulari corresponent al tipus triat. Es pot emprar el mateix formulari per tot, però amb camps pre-emplenats i/o ocults en funció del tipus d’enviament, o bé fer formularis independents. Per exemple, a comunicacions SIR hauria de venir pre-emplenat (i no modificable) el tipus com “Administració pública”, i no hauria d’haver possibilitat de triar destinataris.

A la part superior de la pantalla de cada tipus d’enviament, hauria d’aparèixer un text explicatiu breu sobre el tipus d’enviament concret que s’ha triat, quan s’ha d’emprar, i quines alternatives hi han. Aquests textos els definiríem noltros

**Comment by acuevas-dgtic** [comment]
S'ha d'actualitzar el manual

**Comment by josepg-limit** [comment]
inclosa dins la issue #556
