### ISSUE TITLE
Canvis al formulari d'enviament

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#556]
Canvis generals a tots els formularis:
    1. Quan es fa un nou enviament, el formulari es diu sempre “Alta de notificació”. El nom s’hauria de correspondre amb el tipus d’enviament concret (Notificació, Comunicació o Comunicació SIR).
    2. El camp telèfon de l’interessat (Titular) s’hauria d’eliminar, ja que no existeix a Notifica, i a les comunicacions SIR no té sentit.

Pel cas específic del formulari de comunicacions SIR:
    1. S’hauria d’eliminar l’opció de “Tipus de servei”, ja que només té sentit per enviaments amb CIE.
    2. El camp de correu electrònic, actualment no es fa servir. Una de dues: o s’envia un correu electrònic d’avís, o s’elimina el camp.
    3. S’hauria d’eliminar l’apartat DESTINATARIS, ja que als enviaments SIR la figura del representant no existeix.
    4. S’ha d’eliminar l’opció “Nou enviament”. Els enviaments SIR han de ser individuals, no es pot fer un enviament múltiple.

**Comment by acuevas-dgtic** [comment]
Falta afegir un asterisc al camp procediment dins d'una notificació

![image](https://user-images.githubusercontent.com/58417501/135254111-4562a134-7930-4da7-9526-81a5a50b67db.png)

**Comment by josepg-limit** [comment]
solucionat al commit: bb06116b65fa798240dd4ba9c9075c97e8067a48

**Comment by acuevas-dgtic** [comment]
Si el formulari de comunicació SIR dóna error de validació apareixen camps apareixen els camp Correu electrònic i tipus

![image](https://user-images.githubusercontent.com/58417501/135596723-72f87180-f39b-46e4-9061-0a1e2f813fad.png)
