### ISSUE TITLE
Error al actualizar órganos gestores

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#589]
Al actualizar los órganos gestores, han quedado todos en estado obsoleto.

**Comment by acuevas-dgtic** [comment]
He actualizdad los órganos y han quedado todos en estado obsoleto

**Comment by acuevas-dgtic** [comment]
Al formulari d'alta apareix el literal "llibre" duplicat Hauria de possar Òrgan

![imatge](https://user-images.githubusercontent.com/58417501/129547724-efd7d146-2077-49e2-806b-94e441484662.png)
