### ISSUE TITLE
Error en cridar a Notib amb un número de referència que conté //

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#593]
Error en cridar Notib amb un número de referència que conté doble barra. Substitueix les dues barres per una.

Exemple:
Quan consultes un enviament amb la referència 8vzkicPF//A=
Retorna el següent error:

- No s'ha trobat cap enviament amb la referència 8vzkicPF/A=

**Comment by jvazquez-dgtic** [comment]
en el listado de envios al intentar filtrar por "Codi NOTIB de l'enviament" no surte ningún efecto
