### ISSUE TITLE
No es mostren bé els caracters especials en el resum dels enviaments massius

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#605]
![imatge](https://user-images.githubusercontent.com/58417501/129889429-bce21f9b-02be-4069-9079-7132166e17cd.png)

**Comment by josepg-limit** [comment]
El problema estava en que acceptam fitxers amb qualsevol codificació de caràcters, s'ha modificat el codi de manera que el programa acerta automàticament la codificació del fitxer introduït i el processi en conseqüència
