### ISSUE TITLE
Revisar problema de sincronització de rols d'usuari i seycon

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#609]
Tenim molts problemes amb els rols d'usuari en producció cada vegada que desplegam i reiniciam el jboss. Per exemple, jo tinc els rols NOT_ADM, NOT_SUPER, NOT_DGTECNOLOGIC i NOT_USER i moltes vegades no me surt el rol NOT_SUPER ni en la configuració d'usuari ni l'enllaç en els perfils d'usuari. De vegades tenim que reiniciar l'aplicació fins a 3 o 4 vegades (esborrant temporals) perquè els agafi bé.

S'ha de revisar si és un problema del Jboss, del plugin d'usuari o de la caché de l'aplicació. Aquesta problemàtica només la hem detectada en NOTI; en RIPEA i DISTRIBUCIO que també utilitzen rols i no s'ha donat mai aquest problema.

**Comment by acuevas-dgtic** [comment]
El botó "Refrescar rols" pareix que no fa res. S'ha d'eliminar

**Comment by acuevas-dgtic** [comment]
El modal de detall d'usuari del monitor d'integracions no funciona la primera vegada (has d'anar a altra pipella i tornar a la de Usuaris).

A més, els detalls no es visualitzen bé.
![imatge](https://user-images.githubusercontent.com/58417501/132177727-564f4b6a-b560-4466-8bc1-ddc131a14017.png)

**Comment by josepg-limit** [comment]
S'ha modificat la lògica de manera que el problema s'arregli al tancar i tornar a obrir la sessió de l'usuari

**Comment by jvazquez-dgtic** [comment]
parece que esto no acaba de ir bien, la dgmad tiene el rol configurado:
![imatge](https://user-images.githubusercontent.com/86109941/135093489-57717813-508c-450b-afc9-3929c338dfcb.png)

mi usuario tiene ese mismo rol configurado:
![imatge](https://user-images.githubusercontent.com/86109941/135093578-9073e521-9c02-441e-b23f-5dd2286bcc68.png)

aun asi aparece este mensaje y no puedo seleccionar ningún OG:
![imatge](https://user-images.githubusercontent.com/86109941/135093718-36fd2067-21a6-4f12-82d0-a0bb7bbedeb7.png)

**Comment by jvazquez-dgtic** [comment]
al añadir el rol NOT_DG_DESTECNOLOGIC y desconectarme y volverme a conectar en mi configuración de usuario aparece que tengo el rol:
![imatge](https://user-images.githubusercontent.com/86109941/135598815-3f92eecd-6bcb-40fe-920a-d261066eedd4.png)
Por lo tanto la aplicación si se connecta correctamente con el seycon. Pero no me deja realizar ninguna acción asociada a ese rol, en la consulta de remesses aparece este mensaje:
![imatge](https://user-images.githubusercontent.com/86109941/135599117-cc07904b-da6e-4bea-ada9-48897f65e8c1.png)
al intentar hacer un nuevo envio aparece este otro mensaje y no puedo seleccionar ningun organo gestor:
![imatge](https://user-images.githubusercontent.com/86109941/135599234-9dc9fda8-5b27-4036-9d73-43b5dc58b829.png)
 y como se puede comprobar en la siguiente imagen ese rol deberia darnos acceso a la dgmad:
![tempsnip](https://user-images.githubusercontent.com/86109941/135600209-ef72a998-9b2c-4300-be59-ee6b153dd7a1.png)
 he intentado eliminar las cookies y cambiarme varias veces el rol y sigue sin funcionar.

**Comment by acuevas-dgtic** [comment]
Pareix que s'ha solucionat
