### ISSUE TITLE
Afegir @ el camp "Concepte" en els enviaments massius

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#610]
Actualmente el envío masivo no acepta el caracter "@" en el campo "Concepto";  muestra el siguiente error: 
`[1032] El format del camp concepte no és correcte. Inclou els caràcters (@) que no són correctes`

Hay que determinar si es una limitación de Notifica o del registro

**Comment by josepg-limit** [comment]
El caràcter "@" en el concepte és invàlid per una restricció de **notifica**, tal com està descrit al seu manual d'usuari:
![imagen](https://user-images.githubusercontent.com/17267008/133223016-7566b37e-6736-46aa-8713-71bf283829f3.png)
