### ISSUE TITLE
Accions massives en la consulta de remeses i en la consulta d'enviaments

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#611]
Accions disponibles per usuaris:
- [x] Exportar a full de càlcul. Exporta els resultat a un full de càlcul
- [x] Reintentar remeses/enviaments pendents. No disponible si la remesa o enviament està en estat enviant, enviada o processada.
- [x] Actualitzar estat. Des de Notifica i SIR.
- [x] #616
- [x] Esborrar. Només si están en estat "Pendent".

Accions disponibles només per a administradors d'entitat (a més de les anteriors):
- [x] Reintentar registre (substitueix a la secció "Gestió > Notificacions amb error de registre")
- [x] Reactivar consultes a Notifica
- [x] Reactivar consultes a SIR
- [x] "Reactivar callbacks"

**Comment by jvazquez-dgtic** [comment]
Al realizar acciones masivas en la consulta de remeses, si pulsamos sobre actualizar estado si esta procesada y rehusada aparece rehusada 2 veces. Adjunto caputra:
![imatge](https://user-images.githubusercontent.com/86109941/135090131-e38ca46c-066a-47c3-83e6-abdc3bf764f7.png)

**Comment by acuevas-dgtic** [comment]
Si ocurre es algo temporal ya que cuando lo vuelves a buscas sale bien.

**Comment by acuevas-dgtic** [comment]
Ara no es poden seleccionar les remeses
