### ISSUE TITLE
Problema per a marcar remeses com a processades

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#612]
Amb permís de processar sobre òrgan, només es poden marcar com a processades les comunicacions sense procediment.

Això és un error, i s'han de poder marcar com a processades les remeses amb procediment

![image](https://user-images.githubusercontent.com/17267008/131831462-86c75e23-f3b4-4440-acd3-5d448002cbe7.png)
![image](https://user-images.githubusercontent.com/17267008/131831487-912cb0ea-e9ad-4078-8fae-954b5c26a7df.png)

**Comment by acuevas-dgtic** [comment]
Se ha solucionado para los usuarios normales pero no para los administradores
