### ISSUE TITLE
Modificar l'ordenació dels botons consulta d'enviaments

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#633]
A la pantalla de consulta d'enviaments pareix que el botó de neteja dels filtres pertany a les opcions per seleccionar enviaments per les accions massives.
Quedaria més clar si és juntás amb el botó de visualització i no amb els d'accions massives.
Així és com està:
![imatge](https://user-images.githubusercontent.com/86109941/135613767-6f6f6579-770e-480e-a255-9d2cfed1903f.png)

Així és com hauria de quedar:
![netejar](https://user-images.githubusercontent.com/86109941/135613701-2153ea57-0818-441a-8575-08ba8879af48.png)

**Comment by acuevas-dgtic** [comment]
implementado
