### ISSUE TITLE
Creació d'un òrgan sense òrgan gestor

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#636]
Per a poder fer la prova hem assignat un llibre i una oficina a nivell d'entitat.  L'òrgan gestor no es crea, però no es mostra cap missatge a l'usuari.

**Comment by josepg-limit** [comment]
Amb la sincronització d'òrgans gestors, ja no es creen òrgans manualment.
Per tant aquesta tasca ja no té sentit.
