### ISSUE TITLE
Revisar apòstrofs en la finestra d'actualització de procediments

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#637]
![image](https://user-images.githubusercontent.com/58417501/135985917-2b6e22f4-f4f6-4f62-aeb5-8c3a5c82b73c.png)

**Comment by jvazquez-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/86109941/152125308-85b1cd6e-0888-4fa1-a7c4-7bbd17c40278.png)
