### ISSUE TITLE
Omplir checkbox de PDF firmat amb documents de CSV

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#640]
Al enviar un documento csv deberia obtener los datos del documento y rellenar el checkbox de PDF firmat

![imatge](https://user-images.githubusercontent.com/86109941/135238492-7e3d4294-bcb7-4638-8cc6-0ab700089764.png)

**Comment by josepg-limit** [comment]
S'ha comprovat que actualment s'obté la informació del dpcument i s'emplena el camp pdf firmat.

![imatge](https://user-images.githubusercontent.com/17267008/143890283-37bdd6a2-986f-4eef-9956-3a69533b244e.png)
