### ISSUE TITLE
Mostrar la data de finalització en la columna estat de la consulta de remeses

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#644]
En el listado de remesas en el caso de que estuviesen finalizadas, ya sea por expirada, aceptada o rechazada deberia aparecer la fecha en la que se ha aceptado, rechazado o en la que ha expirado de la misma manera que aparece en las procesadas.

**Comment by jvazquez-dgtic** [comment]
algunos datos no salen 
![imatge](https://user-images.githubusercontent.com/86109941/140914827-6e2ac4c0-f090-466f-a9aa-0125d8574b30.png)

**Comment by jvazquez-dgtic** [comment]
No aparece bien la fecha de processamiento, por ej el id 4620670 aparece con la fecha de finalización y no de procesamiento

**Comment by acuevas-dgtic** [comment]
Sigue sin aparecer la fecha de procesamiento
