### ISSUE TITLE
Desactivar botó d'enviar en enviaments massius

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#648]
los usuarios podrian pulsar varias veces el boton de enviar al hacer envios masivos, seria recomendable desactivar el boton una vez se pulsa para evitar que se pulse varias veces y se duplique el envio masivo

**Comment by josepg-limit** [comment]
Modificat en versió anterior, on es mostra un missatge indicant que s'està executant la acció, i no permet interactuar amb el formulari.
