### ISSUE TITLE
no se ve correctamente el menu de acciones en las remesas

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#654]
el menu de acciones del listado de remesas no se ve correctamente, queda cortado (debajo) por la parte lateral derecha:
![imatge](https://user-images.githubusercontent.com/86109941/137888462-912c035c-9ab7-4f55-87e3-c05ab7c7a8c6.png)

**Comment by acuevas-dgtic** [comment]
Parece resuelto
