### ISSUE TITLE
Corregir literal d'error al no trobar el document en un enviament massiu

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#676]
corregir el literal de l'error quan no es troba un document del llistat de enviaments massius:
Sha produït un error inesperat al processar lenviament massiu [ Fila: 1, Columna: 5 - Nombre Fichero]:
Error obtenint el document
null

**Comment by jvazquez-dgtic** [comment]
En castellà també esta malament:
Se ha producido un error inesperado al procesar el envio masivo [ Fila: 1, Columna: 5 - Nombre Fichero]:
Error obtenint el document
null 

te errades i te una part en que surt en català.

**Comment by josepg-limit** [comment]
S'han revisat tot el multiidioma de les validacions a l'hora de donar d'alta notificacions i enviaments massius.
S'han afegit molts missatges a multiidioma i s'han arreglat problemes amb caràcters especials a altres

**Comment by jvazquez-dgtic** [comment]
S'han de revisar els textos ja que contenen errors.
![imatge](https://user-images.githubusercontent.com/86109941/152126774-bd4d8823-6b72-48c1-bf20-e470d6ea0681.png)
