### ISSUE TITLE
Comunicacions via SIR no han d'admetre CSIG, HTML i CSV

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#681]
Les comunicacions via SIR no admeten CSIG, HTML i CSV. NOTIB les esta admetent i posteriorment fallen a registre.

**Comment by acuevas-dgtic** [comment]
Se han d'admetre: JPG, JPEG, ODT, ODP, ODS, ODG, DOCX, XLSX, PPTX, PDF, PNG, RTF, SVG, TIFF, TXT, XML, XSIG, CSIG, HTML i CSV. Pareix un problema de registre

**Comment by jvazquez-dgtic** [comment]
Finalment s'han d'eliminarels formats CSIG, HTML i CSV dels enviaments via sir

**Comment by jvazquez-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/86109941/152128384-add33853-caa6-4d14-990f-61afed9eaa4f.png)
comunicación
