### ISSUE TITLE
Corregir literals d'error d'enviaments massius

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#686]
Pareix que els literals en català necessiten corregir-se, quan es fa un enviament massiu i no es troba un document del csv apareix sense apòstrof:
Sha produït un error inesperat al processar lenviament massiu [ Fila: 1, Columna: 5 - Nombre Fichero]:
Error obtenint el document
null 

a més a més en castellà apareix una part en català:

Se ha producido un error inesperado al procesar el envio masivo [ Fila: 1, Columna: 5 - Nombre Fichero]:
Error obtenint el document
null

**Comment by jvazquez-dgtic** [comment]
rel. amb issue #667

**Comment by josepg-limit** [comment]
Solventat a la issue #676
