### ISSUE TITLE
Millorar la comprobació del camp de correu electrònic

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#688]
al crear un nou enviament quan introduïm el camp correu ens permet introduir correus que evidentment no son vàlids, per exemple a@a

**Comment by jvazquez-dgtic** [comment]
al intentar hacer una comunicación con el correo: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@hotmail.com
da error de formato incorrecto, el formato parece correcto

**Comment by josepg-limit** [comment]
Segons la [RFC 3696](http://www.rfc-editor.org/rfc/rfc3696.txt), la longitud màxima de la part local de l'adreça de correu electrònic no pot superar els 64 caràcters.

>   In addition to restrictions on syntax, there is a length limit on
>   email addresses.  That limit is a maximum of 64 characters (octets)
>   in the "local part" (before the "@") and a maximum of 255 characters
>   (octets) in the domain part (after the "@") ...

Per tant és correcte que es mostri el missatge de format incorrecte.
