### ISSUE TITLE
Permetre fer dos enviaments a una comunicació o notificació

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#690]
Visualment es permet fer dins una comunicació 2 o més enviaments però quan s'envia a registre no es fa correctament i es retorna un error indicant que no es poden indicar 2 interessats.
Al enviar-se la comunicació a registre s'envia un únic enviament amb 2 interessats i haurien de ser 2 enviaments cada un amb un interessat.

**Comment by acuevas-dgtic** [comment]
Hi ha d'haver un registre de sortida per cada enviament

**Comment by josepg-limit** [comment]
S'ha d'afegir lògica per a controlar els errors de registre.
Una notificació amb múltiples enviaments pot tenir enviaments registrats correctament i altres amb error. Al reintentar el registre s'ha de registrar només els enviaments amb error.
No s'enviarà la notificació a Notifica fins que tots els enviaments no es estiguin registrats.

**Comment by jvazquez-dgtic** [comment]
segueix donant el mateix error

**Comment by jvazquez-dgtic** [comment]
a notifica dona l'error:
[4020] Referencia emisor demasiado larga, tamaño máximo 20 caracteres
