### ISSUE TITLE
Permetre filtrar per aplicació en el monitor d'integracions - callback client

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#703]
Afegir també una columna amb l'usuari que realitzar l'enviament.

![image](https://user-images.githubusercontent.com/58417501/154665368-6b0af6bc-3525-47c9-a3bc-89fc930c33c2.png)

**Comment by acuevas-dgtic** [comment]
El filtre no funciona. La columna Aplicació està buida

**Comment by josepg-limit** [comment]
Es va afegir informació del client, per a poder filtrar a les operacions de sortida cap als clients.
Es procedeix a afegir aquesta informació a totes les operacions d'entrada, provinents de clients.
