### ISSUE TITLE
Error 500 Invalid User

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#707]
Si trabajas con varios perfiles de vez en cuando aparece un error 500 y la única forma de acceder es abriendo una nueva ventana de incógnito

![image](https://user-images.githubusercontent.com/58417501/155512416-52cceae6-b1cf-4b52-b0d0-15148279cb28.png)

**Comment by acuevas-dgtic** [comment]
Este error parece que ya no se produce

**Comment by acuevas-dgtic** [comment]
Vuelve a aparecer

**Comment by josepg-limit** [comment]
Se intentará evitar el error, o como mínimo añadir un botón para poder ir a la página de inicio sin necesidad de abrir una página de incógnito.

Si es necesario trabajar con varios perfiles, en firefox recomendamos el uso de la extensión [Multi-Account Containers](https://addons.mozilla.org/ca/firefox/addon/multi-account-containers/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), que permite abrir pestañas con sesiones independientes.
