### ISSUE TITLE
Casuística de notificaciones a extranjeros

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#709]
Cuando el destinatario de una notificación es extranjero, al no tener NIF, no tiene carpeta ciudadana y no puede ver las notificaciones, pero el registro de salida sí debería hacerse. Por tanto, para estos casos NOTIB debería hacer el registro de salida, y luego enviar el contenido de la notificación vía correo electrónico.

**Comment by jvazquez-dgtic** [comment]
no es registren, dona error
![imatge](https://user-images.githubusercontent.com/86109941/160603903-4a1a6b46-ecca-40db-b88c-405eb10f44e5.png)

**Comment by jvazquez-dgtic** [comment]
En el correu apareixen tots els camps en català tant a la part en castellà com a la part en català.
En el camp "Informació adicional"  tant al missatge en castellà com en català apareix amb un valor "null".
Al missatge en castellà i en català apareix l'organisme amb un aprostrof final "(govern de les Illes **Balears)'"**

**Comment by jvazquez-dgtic** [comment]
quan es fa l'enviament amb un representant amb dni a notifica dona l'error:
[4020] Referencia emisor demasiado larga, tamaño máximo 20 caracteres

**Comment by jvazquez-dgtic** [comment]
al hacer un envio a un extrangero con un representante aparece el error:
[4200] El nif "XXXX" no tiene un formato válido.
donde XXX es el código de la identificación del extrangero
