### ISSUE TITLE
Afegir número d'errors en el momitor d'integracions

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#721]
Similar a com es fa al monitor de distribució 

![image](https://user-images.githubusercontent.com/58417501/161732570-582c52b0-c060-434e-b294-f106a1a9c3b9.png)

**Comment by jvazquez-dgtic** [comment]
A algunes pestanyes apareix el codi de l'entitat i a unes altres el nom de l'entitat. S'hauria d'unificar i posar sempre el nom.
Inclús de vegades pasa a la mateixa pantalla.
![imatge](https://user-images.githubusercontent.com/86109941/182336703-65445d86-f6d3-4a34-9b9b-ed79096a603a.png)
