### ISSUE TITLE
Revisar aparició de warning a l'estat del llistat de remeses

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#722]
pareix que no sempre surt el warning quan hi ha un error a un enviament.
![image](https://user-images.githubusercontent.com/86109941/161740896-ad643897-273c-490f-947e-645f06ac51b1.png)
es un enviament duplicat, a l'enviament que surt el warning amb l'error es perque s'ha forçat una altre vegada l'enviament i ja a aparegut pero sino no apareixia.

Antes pareix que sempre apareixia i ara ja no

**Comment by josepg-limit** [comment]
No ha estat possible reproduïr aquest comportament.
Sembla que ja s'ha arreglat degut a canvis realitzats en altres issues.
