### ISSUE TITLE
Canvi en el sistema de permisos a nivell d'òrgan

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#741]
El sistema de permisos ha de quedar de la siguiente manera:

A nivel de órgano:

- Notificacions i comunicacions amb procediment d'òrgan : Permite realizar notificaciones y comunicaciones (SIR y no SIR)  sobre TODOS los procedimientos y servicios de un órgano concreto y sus descendientes.
- Notificacions i comunicacions amb procediment comú: Permite realizar notificaciones y comunicaciones (SIR y no SIR)  sobre TODOS los procedimientos y servicios comunes a nivel de un órgano concreto.
- Comunicacions sense procediment: : Permite realizar cualquier tipo de comunicación (SIR y no SIR) a nivel de òrgano sin procedimiento o servicio asociado.

A nivel de procedimiento o servicio:

- Notificacions i comunicacions: Permite realizar notificaciones y comunicaciones No SIR sobre un procedimiento o servicio concreto.
- Comunicacions SIR: Permite realizar comunicaciones SIR sobre un procedimiento o servicio concreto.

**Comment by jvazquez-dgtic** [comment]
para clarificar, se quiere poder dar los siguentes tipos de permisos:
1 Comunicaciones SIR y comunicaciones sin SIA
2 Notificaciones y comunicaciones sobre SIAs concretos
3 Barra libre a todo el DIR3

**Comment by acuevas-dgtic** [comment]
- [ ] El acceso al listado de órganos es muy lento. 
- [ ] Formulario y listado: Habría que añadir un tooltip a cada tipo de permiso con un texto que explique para qué sirve cada uno.
- [ ] La disposición de los textos  del listado de permisos es farragosa. Mejor que cada letra esté en una columna peor sin girar.
- [ ] Añadir el icono que aparece en el formulario de nuevo permiso en el listado de permisos

**Comment by jvazquez-dgtic** [comment]
Al seleccionar comunicacions sense procediment no aparece el desplegable de hacer un nuevo envio.
Al seleccionar comunicacions SIR al hacer una nueva comunicación aparecen todos los procedimientos propios del organo.
En el listado de remeses tenemos visibilidad de remesas para procedimientos para los que no tenemos permisos, lo mismo pasa en el listado de enviaments

**Comment by acuevas-dgtic** [comment]
Hay que controlar los permisos que tenemos definidos actualmente a nivel de órgano y a nivel de procedimiento para que los usuarios no se vean afectados. Si se tiene activado el permiso antiguo "Notificacions i comunicacions" en el nuevo sistema han de estar marcados "Notificacions" y "Comunicacions" por separado.

**Comment by josepg-limit** [comment]
S'han afegit els tooltips als llistat de permisos de procediments, serveis i òrgans.
Per ara s'ha deixat únicament amb la icona a la capçalera:
![imatge](https://user-images.githubusercontent.com/17267008/210411017-ed4b39d1-ecf8-457d-a911-5e30aa9ee033.png)

ja que el text vertical consideram que no queda massa bé:
![imatge](https://user-images.githubusercontent.com/17267008/210410962-94682a76-8dbf-459d-88a1-cefc857729c5.png)

Si es considera que s'ha de posar el nom en vertical ho afegirem sense problema.

**Comment by josepg-limit** [comment]
Per a afegir el permís de comunicacions als usuaris i rols que actualment tenen el permís de notificació (el que fins ara era "Notificacions i comunicacions") s'ha d'executar el següent script:
```
INSERT INTO not_acl_entry (acl_object_identity, ace_order, sid, mask, granting, audit_success, audit_failure)
SELECT acl_object_identity, ace_order, sid, 8192, granting, audit_success, audit_failure 
FROM not_acl_entry
WHERE mask = 1024;
```
