### ISSUE TITLE
Revisar el funcionament del monitor de integracións

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#747]
Parece que algunos logs solo empiezan a guardarse una vez entras en el monitor de integraciiones, hasta entonces no guarda ningun log

**Comment by acuevas-dgtic** [comment]
Algo no funciona bien

![image](https://user-images.githubusercontent.com/58417501/207848306-ac1c62a9-40f7-4410-b0a6-541dac0df20d.png)

**Comment by josepg-limit** [comment]
Modificat en el commit: 
a6ec806e567411805662dadfab394d757fc9110e
