### ISSUE TITLE
Revisar la paginació dels procediments/serveis desde rolsac

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#748]
Pareix que hi ha procediments que no s'actualitzen, l'error pareix estar en la paginació d'aquests. Comprobar que els serveis funcionen bé.

**Comment by josepg-limit** [comment]
Commits de la tasca:
221b4cddaaf1796df38a791bc42d8aaa77e2e7db
830a64dbbf2c4e3974fb2fa31c6ffadb36271ba1
