### ISSUE TITLE
Validar la firma d'un document firmat abans d'enviar a Registre

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#755]
Si s'envia un document firmat amb firma invàlida no e spot registrar. Per tant, s'ha de realitzar una validació prèvia en cas d'estar firmat.

**Comment by acuevas-dgtic** [comment]
No deixa enviar cap document

**Comment by acuevas-dgtic** [comment]
Debido a que esta funcionalidad es compleja de configurar, habría que añadir una propiedad que nos permita activar o desactivar la validación previa

**Comment by josepg-limit** [comment]
Al eliminar las librerías de validatesignature del repositori local ha estat possible reproduïr l'error.
Es tractava d'una incompatibilitat de les llibreries de firma en servidor i validació de firma. S'ha augmentat la versió de la llibreria de firma en servidor per a solventar el problema de les dependències.
