### ISSUE TITLE
No permetre fer una exportació a full de càlcul sense seleccionar remeses

### ISSUE THREAD

**Issue by jvazquez-dgtic** [GovernIB/notib#761]
No permetre fer una exportació a full de càlcul sense seleccionar remeses, al llistat de remeses a les accions massives si no selecciones cap remesa dona un error 404 al intentar exportar a full de càlcul.

Revisar la resta d'accions massives a aquesta pàgina i a qualsevol.

**Comment by acuevas-dgtic** [comment]
No se ha podido reproducir
