### ISSUE TITLE
Sincronitzar oficines

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#767]
Per evitar estar realitzant consultes a Dir3 per obtenir les oficines, i optimitzar el llistat d'òrgans, es desaran les oficines a BBDD, i al sincronitzar els òrgans, també s'actualitzaran les oficines.

**Comment by acuevas-dgtic** [comment]
Ya no tiene sentido que el campo oficinas sea editable

![image](https://user-images.githubusercontent.com/58417501/214568272-24e0433c-fa80-4ca9-9280-6789e7556950.png)

**Comment by acuevas-dgtic** [comment]
Si un caso esto podemos hacerlo en una nueva issue que no es urgente.
