### ISSUE TITLE
Ha desaparegut el text de l'estat en el llistat de remeses

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#770]
![image](https://user-images.githubusercontent.com/58417501/214559299-1d6f93ec-1c27-4b1c-9c62-fb99184882c9.png)

**Comment by acuevas-dgtic** [comment]
També afecta altres estats

**Comment by acuevas-dgtic** [comment]
![image](https://user-images.githubusercontent.com/58417501/214560148-8f247979-f2a0-45fb-a5d8-2bd1698d1c31.png)

**Comment by josepg-limit** [comment]
Issue resolta en els commits:
 - 627e72e54602deb4db7bcda8a94192773fc46bde
 - 71ccd27c87f0d4fc85b7910b94375524b4bd8cea
