### ISSUE TITLE
Errors de validació

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/notib#775]
A l'alta de notificació, dona error de validació, quan hi ha apostrofs en el texte

**Comment by acuevas-dgtic** [comment]
Parece que se produce cuando se introduce "´" (acento sin vocal) en lugar de "'" (comilla simple) y cuando se pone "•" en lugar de "·". El mensaje no es claro ya que visualment elo ven igual. Habría que mejorarlo
