### ISSUE TITLE
Validar signatura únicament de documents PDF

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/notib#789]
La validació de la signatura de documents tipus zip està donant error, i com que son documents que en principi no venen signats, llavors no es realitzarà la validació.

**Comment by acuevas-dgtic** [comment]
Crec que aquesta millora es va implementar en la 1.1.22

**Comment by josepg-limit** [comment]
Tasca implementada en els commits ec68eb99 i d6a1f095 de la versió 1.1.22
