### ISSUE TITLE
L'enviament amb identificador XXX ha rebut un callback de l'adviser de tipus 1 quan ja es troba en estat final.

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#798]
De vez en cuando aparecen estos errores en remesas finalizadas. Se debería evitar para no confundir al usuario.

![image](https://user-images.githubusercontent.com/58417501/234849922-055f8219-f97f-42a0-bd4d-d60ad3427925.png)

![image](https://user-images.githubusercontent.com/58417501/234849790-febd9a67-6893-4351-9a4f-55d7fedf0cc9.png)

**Comment by josepg-limit** [comment]
Codi modificat en els commits: 3378a66720c02a54f47568d1f7930102997d00db, ffe74395c1c604fa15b260cae45183c7969d0402 i 5151ab70d5efaccacc06798fb096473fe1da9c30
