### ISSUE TITLE
Correus de canvi d'estat duplicats

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/notib#819]
Pareix que se estan duplicant els enviaments de correus de canvis d'estat a les notificacions.

**Comment by acuevas-dgtic** [comment]
Aquesta errada s'està produint en 1.1.23.7. Revisar si també es produeix en la 2.0.1

**Comment by sandreu-limit** [comment]
Per tal de tenir un major control sobre l'enviament de correus s'han realitzat les següents modificacions:

- S'ha modificat com es realitza la crida a enviar emails, de manera que ara s'envien via events. Això fa que no sigui necessari haver d'esperar a que s'enviïn els correus per finalitzar la tasca, i evita problemàtica al produir-se algun error en els enviaments

- S'ha afegit l'enviament de correus al monitor d'integracions

Al afegir els enviaments de correus a la informació de integració, s'ha detectat que la manera per afegir noves categories al monitor d'integracions era repetitiva (havent de modificar a multiples llocs), i per tant propensa a errors. Per això, també s'ha realitzat una refactorització per a simplificar-ho.
