### ISSUE TITLE
No apareix la raó social en el justificant d'enviament d'una comunicació SIR

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/notib#842]
En alguns casos a la comunicacio SIR, en el justificant d'enviament no surt la rao social
![imagen](https://github.com/GovernIB/notib/assets/65942619/bb8daafa-421a-44dc-b928-9fee0f58f89d)
![imagen](https://github.com/GovernIB/notib/assets/65942619/dda719ca-5347-4083-b0fc-dfe25b474808)

**Comment by acuevas-dgtic** [comment]
Solucionado en la rc40
