### ISSUE TITLE
Quan realitzes un enviament has de desconnectar i tornar-te a conenctar per veure el llistat actualitzat

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#855]
Pareix relacionada amb la #846

**Comment by acuevas-dgtic** [comment]
Continua donat problemes. És cert que apareix al llistat una vegada enviat el formulari, però desapareix quan pitjes el botó filtrar. Torna a aparèixer quan pitjes el botó netejar.

**Comment by josepg-limit** [comment]
Relacionat amb els commits: 160da6917cf37bf03b3a05d986052fbcf128f6eb i 378f6064c13de680b3d4a361d411ed4156a70e22

**Comment by acuevas-dgtic** [comment]
Pareix que ja funciona normalment
