### ISSUE TITLE
¿Existe alguna forma para la SincronizacionEnviosOE de Notific@ v2.1?

### ISSUE THREAD

**Issue by rodrigotabsan** [GovernIB/notib#858]
Buenos días,

Tal y como indica el título, me gustaría saber si está implementada la función SincronizacionEnviosOE de Notific@.

Muchas gracias.

Un saludo.

**Comment by acuevas-dgtic** [comment]
Este no es el canal de comunicación. Envíe un correo a suport@caib.es
