### ISSUE TITLE
Esborrar documents de filesystem enviats des de CSV o UUID que estiguin a l'arxiu

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#911]
Relacionada amb #910. Esborrar del filesystem tots els documents que estiguin a l'arxiu. Els documents han d'estar accesibles des de les remeses corresponent amb un enllaç a l'arxiu o ConCSV.

**Comment by josepg-limit** [comment]
No es guardaven els fitxers CSV o UUID al sistema de fitxers. Per tant no hi ha res a esborrar. 
De totes formes per tal d'alliberar espai de disc s'ha creat un procediment per esborrar els fitxers que no estiguin refrenciats en la base de dades de Notib.
