### ISSUE TITLE
Enviaments massius: Error retornat per Notifica: [4312] No hay documento asociado al elemento contenido ni URL en enlaceDocumento

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#917]
Relacionada amb #915.

Hem detectat casos d'enviaments massius on s'està enviant el mateix document i alguns enviaments funcionen i d'altres mostren l'error:

`Error retornat per Notifica: [4312] No hay documento asociado al elemento contenido ni URL en enlaceDocumento`

Al accedir al detall dels enviaments que han fallat surt aquest error

![image](https://github.com/GovernIB/notib/assets/58417501/2f3dcd21-f591-4510-b295-dec8d5de2fd0)

En canvi, els que han anat bé es pot descarregar sense problemes.

**Comment by josepg-limit** [comment]
Resolt a la #915
