### ISSUE TITLE
Revisar si l'acció "Esborrar" d'una remesa esborra també els documents adjunts

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#927]
Si s'esborra una remesa que ha donat error, s'hauria d'esborrar també els documents adjunts. Revisar si s'està fent.

**Comment by josepg-limit** [comment]
Actualment les remeses no s'esborren fisicament de la base de dades. Quan s'apreta esborrar es marquen com a esborrades i existeix la posibilitat de recuperar-les. Per tant no es poden esborrar els seus fitxers associats.
