### ISSUE TITLE
Revisar si s'estan duplicant els documents en els enviaments massius

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#928]
Un document pot apareixen vàries vegades en un enviament massiu però només s'hauria d'emmagatzemar una vegada al filesystem. Comprovar que és així. Si s'ha produït aquest comportament, s'hauria d'executar qualque script per solucionar-ho.

**Comment by josepg-limit** [comment]
Resolt al commit 43f3ef54548ff8d52f07f89d3fc8e9ef4e311c61
