### ISSUE TITLE
Remeses en estat Enviada que realment no s'han enviat

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#939]
Tenim remeses en estat "Enviada" que realment no s'han enviat. L'estat de l'enviament és "Pendent d'enviar". Apareixen cada cert temps, no són molt antigues. S'haurien de corregir i evitar que aquesta situació es torni a produir.

![image](https://github.com/user-attachments/assets/7c0c893e-bb4a-4e1e-8c37-0f156713421a)

Detalls remesa:
![image](https://github.com/user-attachments/assets/b329fcd8-c710-4e51-84f6-6a2261ed64f3)

Detals enviament:
![image](https://github.com/user-attachments/assets/2f0f6147-6ea0-410f-9cda-e16054e9c871)

![image](https://github.com/user-attachments/assets/1c884f98-25ce-44e4-96a5-0a4566e0b961)

**Comment by josepg-limit** [comment]
Issue resolta a la #937
