### ISSUE TITLE
Remeses en estat Registrada que realment s'han enviat a Notifica

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#940]
Apareixen remeses en estat Registrada que realment s'han enviat a Notifica. Pareix que no s'ha actualitzar l'estat de la remesa una vegada realitzat l'enviament

![image](https://github.com/user-attachments/assets/e077d2a1-6647-4416-94b3-4c7daba6c6a2)

Detalls de la notificació
![image](https://github.com/user-attachments/assets/daaba974-965a-48f3-80b5-d52b3bc5cc45)

Detalls de l'enviament
![image](https://github.com/user-attachments/assets/c3a8b3eb-ce94-4a6c-bb34-fc534fa875d3)

**Comment by josepg-limit** [comment]
Issue resolta a la #937
